// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: AddChatRoomMember.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddChatRoomMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest           *BaseRequest      `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	MemberCount           *uint32           `protobuf:"varint,2,req,name=memberCount" json:"memberCount,omitempty"`
	MemberList            []*MemberReq      `protobuf:"bytes,3,rep,name=memberList" json:"memberList,omitempty"`
	ChatRoomName          *SKBuiltinStringT `protobuf:"bytes,4,req,name=chatRoomName" json:"chatRoomName,omitempty"`
	LastRoomMsgTimeStamp  *uint32           `protobuf:"varint,5,opt,name=lastRoomMsgTimeStamp" json:"lastRoomMsgTimeStamp,omitempty"`
	AccessApplicationDesp *string           `protobuf:"bytes,6,opt,name=accessApplicationDesp" json:"accessApplicationDesp,omitempty"`
	History               *HistoryInfo      `protobuf:"bytes,7,opt,name=history" json:"history,omitempty"`
}

func (x *AddChatRoomMemberRequest) Reset() {
	*x = AddChatRoomMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AddChatRoomMember_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddChatRoomMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChatRoomMemberRequest) ProtoMessage() {}

func (x *AddChatRoomMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AddChatRoomMember_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChatRoomMemberRequest.ProtoReflect.Descriptor instead.
func (*AddChatRoomMemberRequest) Descriptor() ([]byte, []int) {
	return file_AddChatRoomMember_proto_rawDescGZIP(), []int{0}
}

func (x *AddChatRoomMemberRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *AddChatRoomMemberRequest) GetMemberCount() uint32 {
	if x != nil && x.MemberCount != nil {
		return *x.MemberCount
	}
	return 0
}

func (x *AddChatRoomMemberRequest) GetMemberList() []*MemberReq {
	if x != nil {
		return x.MemberList
	}
	return nil
}

func (x *AddChatRoomMemberRequest) GetChatRoomName() *SKBuiltinStringT {
	if x != nil {
		return x.ChatRoomName
	}
	return nil
}

func (x *AddChatRoomMemberRequest) GetLastRoomMsgTimeStamp() uint32 {
	if x != nil && x.LastRoomMsgTimeStamp != nil {
		return *x.LastRoomMsgTimeStamp
	}
	return 0
}

func (x *AddChatRoomMemberRequest) GetAccessApplicationDesp() string {
	if x != nil && x.AccessApplicationDesp != nil {
		return *x.AccessApplicationDesp
	}
	return ""
}

func (x *AddChatRoomMemberRequest) GetHistory() *HistoryInfo {
	if x != nil {
		return x.History
	}
	return nil
}

type AddChatRoomMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse *BaseResponse `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
	MemberCount  *uint32       `protobuf:"varint,2,req,name=memberCount" json:"memberCount,omitempty"`
	MemberList   []*MemberResp `protobuf:"bytes,3,rep,name=memberList" json:"memberList,omitempty"`
	Tips         *string       `protobuf:"bytes,4,opt,name=tips" json:"tips,omitempty"`
}

func (x *AddChatRoomMemberResponse) Reset() {
	*x = AddChatRoomMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AddChatRoomMember_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddChatRoomMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChatRoomMemberResponse) ProtoMessage() {}

func (x *AddChatRoomMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AddChatRoomMember_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChatRoomMemberResponse.ProtoReflect.Descriptor instead.
func (*AddChatRoomMemberResponse) Descriptor() ([]byte, []int) {
	return file_AddChatRoomMember_proto_rawDescGZIP(), []int{1}
}

func (x *AddChatRoomMemberResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *AddChatRoomMemberResponse) GetMemberCount() uint32 {
	if x != nil && x.MemberCount != nil {
		return *x.MemberCount
	}
	return 0
}

func (x *AddChatRoomMemberResponse) GetMemberList() []*MemberResp {
	if x != nil {
		return x.MemberList
	}
	return nil
}

func (x *AddChatRoomMemberResponse) GetTips() string {
	if x != nil && x.Tips != nil {
		return *x.Tips
	}
	return ""
}

var File_AddChatRoomMember_proto protoreflect.FileDescriptor

var file_AddChatRoomMember_proto_rawDesc = []byte{
	0x0a, 0x17, 0x41, 0x64, 0x64, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f,
	0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x4d,
	0x69, 0x63, 0x72, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xe2, 0x02, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2e, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x2a, 0x0a, 0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a,
	0x0c, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x52, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x4d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67,
	0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x34, 0x0a, 0x15, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65,
	0x73, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x70, 0x12,
	0x26, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0xb1, 0x01, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x43,
	0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0b, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x0a, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0a, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_AddChatRoomMember_proto_rawDescOnce sync.Once
	file_AddChatRoomMember_proto_rawDescData = file_AddChatRoomMember_proto_rawDesc
)

func file_AddChatRoomMember_proto_rawDescGZIP() []byte {
	file_AddChatRoomMember_proto_rawDescOnce.Do(func() {
		file_AddChatRoomMember_proto_rawDescData = protoimpl.X.CompressGZIP(file_AddChatRoomMember_proto_rawDescData)
	})
	return file_AddChatRoomMember_proto_rawDescData
}

var file_AddChatRoomMember_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_AddChatRoomMember_proto_goTypes = []interface{}{
	(*AddChatRoomMemberRequest)(nil),  // 0: AddChatRoomMemberRequest
	(*AddChatRoomMemberResponse)(nil), // 1: AddChatRoomMemberResponse
	(*BaseRequest)(nil),               // 2: BaseRequest
	(*MemberReq)(nil),                 // 3: MemberReq
	(*SKBuiltinStringT)(nil),          // 4: SKBuiltinString_t
	(*HistoryInfo)(nil),               // 5: HistoryInfo
	(*BaseResponse)(nil),              // 6: BaseResponse
	(*MemberResp)(nil),                // 7: MemberResp
}
var file_AddChatRoomMember_proto_depIdxs = []int32{
	2, // 0: AddChatRoomMemberRequest.baseRequest:type_name -> BaseRequest
	3, // 1: AddChatRoomMemberRequest.memberList:type_name -> MemberReq
	4, // 2: AddChatRoomMemberRequest.chatRoomName:type_name -> SKBuiltinString_t
	5, // 3: AddChatRoomMemberRequest.history:type_name -> HistoryInfo
	6, // 4: AddChatRoomMemberResponse.baseResponse:type_name -> BaseResponse
	7, // 5: AddChatRoomMemberResponse.memberList:type_name -> MemberResp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_AddChatRoomMember_proto_init() }
func file_AddChatRoomMember_proto_init() {
	if File_AddChatRoomMember_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	file_MicroRoomBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_AddChatRoomMember_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddChatRoomMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AddChatRoomMember_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddChatRoomMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AddChatRoomMember_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AddChatRoomMember_proto_goTypes,
		DependencyIndexes: file_AddChatRoomMember_proto_depIdxs,
		MessageInfos:      file_AddChatRoomMember_proto_msgTypes,
	}.Build()
	File_AddChatRoomMember_proto = out.File
	file_AddChatRoomMember_proto_rawDesc = nil
	file_AddChatRoomMember_proto_goTypes = nil
	file_AddChatRoomMember_proto_depIdxs = nil
}
