// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: AddContactLabel.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LabelPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LabelName *string `protobuf:"bytes,1,opt,name=labelName" json:"labelName,omitempty"`
	LabelId   *uint32 `protobuf:"varint,2,req,name=labelId" json:"labelId,omitempty"`
}

func (x *LabelPair) Reset() {
	*x = LabelPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AddContactLabel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LabelPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelPair) ProtoMessage() {}

func (x *LabelPair) ProtoReflect() protoreflect.Message {
	mi := &file_AddContactLabel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelPair.ProtoReflect.Descriptor instead.
func (*LabelPair) Descriptor() ([]byte, []int) {
	return file_AddContactLabel_proto_rawDescGZIP(), []int{0}
}

func (x *LabelPair) GetLabelName() string {
	if x != nil && x.LabelName != nil {
		return *x.LabelName
	}
	return ""
}

func (x *LabelPair) GetLabelId() uint32 {
	if x != nil && x.LabelId != nil {
		return *x.LabelId
	}
	return 0
}

type UserLabelInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName    *string `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	LabelIdlist *string `protobuf:"bytes,2,opt,name=labelIdlist" json:"labelIdlist,omitempty"`
}

func (x *UserLabelInfo) Reset() {
	*x = UserLabelInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AddContactLabel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLabelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLabelInfo) ProtoMessage() {}

func (x *UserLabelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_AddContactLabel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLabelInfo.ProtoReflect.Descriptor instead.
func (*UserLabelInfo) Descriptor() ([]byte, []int) {
	return file_AddContactLabel_proto_rawDescGZIP(), []int{1}
}

func (x *UserLabelInfo) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *UserLabelInfo) GetLabelIdlist() string {
	if x != nil && x.LabelIdlist != nil {
		return *x.LabelIdlist
	}
	return ""
}

type AddContactLabelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest   *BaseRequest `protobuf:"bytes,1,opt,name=baseRequest" json:"baseRequest,omitempty"`
	LabelCount    *uint32      `protobuf:"varint,2,opt,name=labelCount" json:"labelCount,omitempty"`
	LabelPairList []*LabelPair `protobuf:"bytes,3,rep,name=labelPairList" json:"labelPairList,omitempty"`
}

func (x *AddContactLabelRequest) Reset() {
	*x = AddContactLabelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AddContactLabel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddContactLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContactLabelRequest) ProtoMessage() {}

func (x *AddContactLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AddContactLabel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContactLabelRequest.ProtoReflect.Descriptor instead.
func (*AddContactLabelRequest) Descriptor() ([]byte, []int) {
	return file_AddContactLabel_proto_rawDescGZIP(), []int{2}
}

func (x *AddContactLabelRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *AddContactLabelRequest) GetLabelCount() uint32 {
	if x != nil && x.LabelCount != nil {
		return *x.LabelCount
	}
	return 0
}

func (x *AddContactLabelRequest) GetLabelPairList() []*LabelPair {
	if x != nil {
		return x.LabelPairList
	}
	return nil
}

type AddContactLabelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse  *BaseResponse `protobuf:"bytes,1,opt,name=BaseResponse" json:"BaseResponse,omitempty"`
	LabelCount    *uint32       `protobuf:"varint,2,opt,name=LabelCount" json:"LabelCount,omitempty"`
	LabelPairList []*LabelPair  `protobuf:"bytes,3,rep,name=LabelPairList" json:"LabelPairList,omitempty"`
}

func (x *AddContactLabelResponse) Reset() {
	*x = AddContactLabelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AddContactLabel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddContactLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContactLabelResponse) ProtoMessage() {}

func (x *AddContactLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AddContactLabel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContactLabelResponse.ProtoReflect.Descriptor instead.
func (*AddContactLabelResponse) Descriptor() ([]byte, []int) {
	return file_AddContactLabel_proto_rawDescGZIP(), []int{3}
}

func (x *AddContactLabelResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *AddContactLabelResponse) GetLabelCount() uint32 {
	if x != nil && x.LabelCount != nil {
		return *x.LabelCount
	}
	return 0
}

func (x *AddContactLabelResponse) GetLabelPairList() []*LabelPair {
	if x != nil {
		return x.LabelPairList
	}
	return nil
}

type UpdateContactLabelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest *BaseRequest `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	LabelPair   *LabelPair   `protobuf:"bytes,2,req,name=labelPair" json:"labelPair,omitempty"`
}

func (x *UpdateContactLabelRequest) Reset() {
	*x = UpdateContactLabelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AddContactLabel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateContactLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContactLabelRequest) ProtoMessage() {}

func (x *UpdateContactLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AddContactLabel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContactLabelRequest.ProtoReflect.Descriptor instead.
func (*UpdateContactLabelRequest) Descriptor() ([]byte, []int) {
	return file_AddContactLabel_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateContactLabelRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *UpdateContactLabelRequest) GetLabelPair() *LabelPair {
	if x != nil {
		return x.LabelPair
	}
	return nil
}

type UpdateContactLabelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse *BaseResponse `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
}

func (x *UpdateContactLabelResponse) Reset() {
	*x = UpdateContactLabelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AddContactLabel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateContactLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContactLabelResponse) ProtoMessage() {}

func (x *UpdateContactLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AddContactLabel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContactLabelResponse.ProtoReflect.Descriptor instead.
func (*UpdateContactLabelResponse) Descriptor() ([]byte, []int) {
	return file_AddContactLabel_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateContactLabelResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

type DelContactLabelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest *BaseRequest `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	LabelIdlist *string      `protobuf:"bytes,2,opt,name=labelIdlist" json:"labelIdlist,omitempty"`
}

func (x *DelContactLabelRequest) Reset() {
	*x = DelContactLabelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AddContactLabel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelContactLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelContactLabelRequest) ProtoMessage() {}

func (x *DelContactLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AddContactLabel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelContactLabelRequest.ProtoReflect.Descriptor instead.
func (*DelContactLabelRequest) Descriptor() ([]byte, []int) {
	return file_AddContactLabel_proto_rawDescGZIP(), []int{6}
}

func (x *DelContactLabelRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *DelContactLabelRequest) GetLabelIdlist() string {
	if x != nil && x.LabelIdlist != nil {
		return *x.LabelIdlist
	}
	return ""
}

type DelContactLabelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse *BaseResponse `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
}

func (x *DelContactLabelResponse) Reset() {
	*x = DelContactLabelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AddContactLabel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelContactLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelContactLabelResponse) ProtoMessage() {}

func (x *DelContactLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AddContactLabel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelContactLabelResponse.ProtoReflect.Descriptor instead.
func (*DelContactLabelResponse) Descriptor() ([]byte, []int) {
	return file_AddContactLabel_proto_rawDescGZIP(), []int{7}
}

func (x *DelContactLabelResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

type ModifyContactLabelListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest       *BaseRequest     `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	UserCount         *uint32          `protobuf:"varint,2,req,name=userCount" json:"userCount,omitempty"`
	UserLabelInfoList []*UserLabelInfo `protobuf:"bytes,3,rep,name=userLabelInfoList" json:"userLabelInfoList,omitempty"`
}

func (x *ModifyContactLabelListRequest) Reset() {
	*x = ModifyContactLabelListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AddContactLabel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyContactLabelListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyContactLabelListRequest) ProtoMessage() {}

func (x *ModifyContactLabelListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AddContactLabel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyContactLabelListRequest.ProtoReflect.Descriptor instead.
func (*ModifyContactLabelListRequest) Descriptor() ([]byte, []int) {
	return file_AddContactLabel_proto_rawDescGZIP(), []int{8}
}

func (x *ModifyContactLabelListRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *ModifyContactLabelListRequest) GetUserCount() uint32 {
	if x != nil && x.UserCount != nil {
		return *x.UserCount
	}
	return 0
}

func (x *ModifyContactLabelListRequest) GetUserLabelInfoList() []*UserLabelInfo {
	if x != nil {
		return x.UserLabelInfoList
	}
	return nil
}

type ModifyContactLabelListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse *BaseResponse `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
}

func (x *ModifyContactLabelListResponse) Reset() {
	*x = ModifyContactLabelListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AddContactLabel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyContactLabelListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyContactLabelListResponse) ProtoMessage() {}

func (x *ModifyContactLabelListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AddContactLabel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyContactLabelListResponse.ProtoReflect.Descriptor instead.
func (*ModifyContactLabelListResponse) Descriptor() ([]byte, []int) {
	return file_AddContactLabel_proto_rawDescGZIP(), []int{9}
}

func (x *ModifyContactLabelListResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

var File_AddContactLabel_proto protoreflect.FileDescriptor

var file_AddContactLabel_proto_rawDesc = []byte{
	0x0a, 0x15, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73,
	0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x09, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x50, 0x61, 0x69, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x07, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x49, 0x64,
	0x22, 0x4d, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x49, 0x64, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x49, 0x64, 0x6c, 0x69, 0x73, 0x74, 0x22,
	0x9a, 0x01, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x0d, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x50, 0x61, 0x69, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0d, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x50, 0x61, 0x69, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x9e, 0x01, 0x0a,
	0x17, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x0d, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x50, 0x61, 0x69, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0d,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x50, 0x61, 0x69, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x75, 0x0a,
	0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x09, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x50, 0x61, 0x69, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x50, 0x61, 0x69, 0x72, 0x52, 0x09, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x50, 0x61, 0x69, 0x72, 0x22, 0x4f, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6a, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2e, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x49, 0x64, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x49, 0x64, 0x6c, 0x69, 0x73,
	0x74, 0x22, 0x4c, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c,
	0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0xab, 0x01, 0x0a, 0x1d, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x3c, 0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x11, 0x75, 0x73, 0x65, 0x72,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x53, 0x0a,
	0x1e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_AddContactLabel_proto_rawDescOnce sync.Once
	file_AddContactLabel_proto_rawDescData = file_AddContactLabel_proto_rawDesc
)

func file_AddContactLabel_proto_rawDescGZIP() []byte {
	file_AddContactLabel_proto_rawDescOnce.Do(func() {
		file_AddContactLabel_proto_rawDescData = protoimpl.X.CompressGZIP(file_AddContactLabel_proto_rawDescData)
	})
	return file_AddContactLabel_proto_rawDescData
}

var file_AddContactLabel_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_AddContactLabel_proto_goTypes = []interface{}{
	(*LabelPair)(nil),                      // 0: LabelPair
	(*UserLabelInfo)(nil),                  // 1: UserLabelInfo
	(*AddContactLabelRequest)(nil),         // 2: AddContactLabelRequest
	(*AddContactLabelResponse)(nil),        // 3: AddContactLabelResponse
	(*UpdateContactLabelRequest)(nil),      // 4: UpdateContactLabelRequest
	(*UpdateContactLabelResponse)(nil),     // 5: UpdateContactLabelResponse
	(*DelContactLabelRequest)(nil),         // 6: DelContactLabelRequest
	(*DelContactLabelResponse)(nil),        // 7: DelContactLabelResponse
	(*ModifyContactLabelListRequest)(nil),  // 8: ModifyContactLabelListRequest
	(*ModifyContactLabelListResponse)(nil), // 9: ModifyContactLabelListResponse
	(*BaseRequest)(nil),                    // 10: BaseRequest
	(*BaseResponse)(nil),                   // 11: BaseResponse
}
var file_AddContactLabel_proto_depIdxs = []int32{
	10, // 0: AddContactLabelRequest.baseRequest:type_name -> BaseRequest
	0,  // 1: AddContactLabelRequest.labelPairList:type_name -> LabelPair
	11, // 2: AddContactLabelResponse.BaseResponse:type_name -> BaseResponse
	0,  // 3: AddContactLabelResponse.LabelPairList:type_name -> LabelPair
	10, // 4: UpdateContactLabelRequest.baseRequest:type_name -> BaseRequest
	0,  // 5: UpdateContactLabelRequest.labelPair:type_name -> LabelPair
	11, // 6: UpdateContactLabelResponse.baseResponse:type_name -> BaseResponse
	10, // 7: DelContactLabelRequest.baseRequest:type_name -> BaseRequest
	11, // 8: DelContactLabelResponse.baseResponse:type_name -> BaseResponse
	10, // 9: ModifyContactLabelListRequest.baseRequest:type_name -> BaseRequest
	1,  // 10: ModifyContactLabelListRequest.userLabelInfoList:type_name -> UserLabelInfo
	11, // 11: ModifyContactLabelListResponse.baseResponse:type_name -> BaseResponse
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_AddContactLabel_proto_init() }
func file_AddContactLabel_proto_init() {
	if File_AddContactLabel_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_AddContactLabel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LabelPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AddContactLabel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLabelInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AddContactLabel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddContactLabelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AddContactLabel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddContactLabelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AddContactLabel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateContactLabelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AddContactLabel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateContactLabelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AddContactLabel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelContactLabelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AddContactLabel_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelContactLabelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AddContactLabel_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyContactLabelListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AddContactLabel_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyContactLabelListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AddContactLabel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AddContactLabel_proto_goTypes,
		DependencyIndexes: file_AddContactLabel_proto_depIdxs,
		MessageInfos:      file_AddContactLabel_proto_msgTypes,
	}.Build()
	File_AddContactLabel_proto = out.File
	file_AddContactLabel_proto_rawDesc = nil
	file_AddContactLabel_proto_goTypes = nil
	file_AddContactLabel_proto_depIdxs = nil
}
