// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: BatchGetContactBriefInfo.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactBriefInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username *string     `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Ret      *int32      `protobuf:"varint,2,opt,name=ret" json:"ret,omitempty"`
	Contact  *ModContact `protobuf:"bytes,3,opt,name=contact" json:"contact,omitempty"`
}

func (x *ContactBriefInfo) Reset() {
	*x = ContactBriefInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BatchGetContactBriefInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactBriefInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactBriefInfo) ProtoMessage() {}

func (x *ContactBriefInfo) ProtoReflect() protoreflect.Message {
	mi := &file_BatchGetContactBriefInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactBriefInfo.ProtoReflect.Descriptor instead.
func (*ContactBriefInfo) Descriptor() ([]byte, []int) {
	return file_BatchGetContactBriefInfo_proto_rawDescGZIP(), []int{0}
}

func (x *ContactBriefInfo) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *ContactBriefInfo) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *ContactBriefInfo) GetContact() *ModContact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type BatchGetContactBriefInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserNameList []string `protobuf:"bytes,1,rep,name=userNameList" json:"userNameList,omitempty"`
}

func (x *BatchGetContactBriefInfoReq) Reset() {
	*x = BatchGetContactBriefInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BatchGetContactBriefInfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetContactBriefInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetContactBriefInfoReq) ProtoMessage() {}

func (x *BatchGetContactBriefInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_BatchGetContactBriefInfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetContactBriefInfoReq.ProtoReflect.Descriptor instead.
func (*BatchGetContactBriefInfoReq) Descriptor() ([]byte, []int) {
	return file_BatchGetContactBriefInfo_proto_rawDescGZIP(), []int{1}
}

func (x *BatchGetContactBriefInfoReq) GetUserNameList() []string {
	if x != nil {
		return x.UserNameList
	}
	return nil
}

type BatchGetContactBriefInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse *BaseResponse       `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
	ContactList  []*ContactBriefInfo `protobuf:"bytes,2,rep,name=contactList" json:"contactList,omitempty"`
}

func (x *BatchGetContactBriefInfoResp) Reset() {
	*x = BatchGetContactBriefInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BatchGetContactBriefInfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetContactBriefInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetContactBriefInfoResp) ProtoMessage() {}

func (x *BatchGetContactBriefInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_BatchGetContactBriefInfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetContactBriefInfoResp.ProtoReflect.Descriptor instead.
func (*BatchGetContactBriefInfoResp) Descriptor() ([]byte, []int) {
	return file_BatchGetContactBriefInfo_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetContactBriefInfoResp) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *BatchGetContactBriefInfoResp) GetContactList() []*ContactBriefInfo {
	if x != nil {
		return x.ContactList
	}
	return nil
}

var File_BatchGetContactBriefInfo_proto protoreflect.FileDescriptor

var file_BatchGetContactBriefInfo_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x42, 0x72, 0x69, 0x65, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x4d, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x42, 0x72, 0x69, 0x65, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x6f, 0x64, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x22,
	0x41, 0x0a, 0x1b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x42, 0x72, 0x69, 0x65, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x22,
	0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x1c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x42, 0x72, 0x69, 0x65, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x42, 0x72, 0x69, 0x65, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_BatchGetContactBriefInfo_proto_rawDescOnce sync.Once
	file_BatchGetContactBriefInfo_proto_rawDescData = file_BatchGetContactBriefInfo_proto_rawDesc
)

func file_BatchGetContactBriefInfo_proto_rawDescGZIP() []byte {
	file_BatchGetContactBriefInfo_proto_rawDescOnce.Do(func() {
		file_BatchGetContactBriefInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_BatchGetContactBriefInfo_proto_rawDescData)
	})
	return file_BatchGetContactBriefInfo_proto_rawDescData
}

var file_BatchGetContactBriefInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_BatchGetContactBriefInfo_proto_goTypes = []interface{}{
	(*ContactBriefInfo)(nil),             // 0: ContactBriefInfo
	(*BatchGetContactBriefInfoReq)(nil),  // 1: BatchGetContactBriefInfoReq
	(*BatchGetContactBriefInfoResp)(nil), // 2: BatchGetContactBriefInfoResp
	(*ModContact)(nil),                   // 3: ModContact
	(*BaseResponse)(nil),                 // 4: BaseResponse
}
var file_BatchGetContactBriefInfo_proto_depIdxs = []int32{
	3, // 0: ContactBriefInfo.contact:type_name -> ModContact
	4, // 1: BatchGetContactBriefInfoResp.baseResponse:type_name -> BaseResponse
	0, // 2: BatchGetContactBriefInfoResp.contactList:type_name -> ContactBriefInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_BatchGetContactBriefInfo_proto_init() }
func file_BatchGetContactBriefInfo_proto_init() {
	if File_BatchGetContactBriefInfo_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	file_ModContact_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_BatchGetContactBriefInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactBriefInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_BatchGetContactBriefInfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetContactBriefInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_BatchGetContactBriefInfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetContactBriefInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_BatchGetContactBriefInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BatchGetContactBriefInfo_proto_goTypes,
		DependencyIndexes: file_BatchGetContactBriefInfo_proto_depIdxs,
		MessageInfos:      file_BatchGetContactBriefInfo_proto_msgTypes,
	}.Build()
	File_BatchGetContactBriefInfo_proto = out.File
	file_BatchGetContactBriefInfo_proto_rawDesc = nil
	file_BatchGetContactBriefInfo_proto_goTypes = nil
	file_BatchGetContactBriefInfo_proto_depIdxs = nil
}
