// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: DownloadAppAttach.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadAppAttachRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest *BaseRequest `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	AppId       *string      `protobuf:"bytes,2,opt,name=appId" json:"appId,omitempty"`
	SdkVersion  *uint32      `protobuf:"varint,3,req,name=sdkVersion" json:"sdkVersion,omitempty"`
	MediaId     *string      `protobuf:"bytes,4,opt,name=mediaId" json:"mediaId,omitempty"`
	UserName    *string      `protobuf:"bytes,5,opt,name=userName" json:"userName,omitempty"`
	TotalLen    *uint32      `protobuf:"varint,6,req,name=totalLen" json:"totalLen,omitempty"`
	StartPos    *uint32      `protobuf:"varint,7,req,name=startPos" json:"startPos,omitempty"`
	DataLen     *uint32      `protobuf:"varint,8,req,name=dataLen" json:"dataLen,omitempty"`
	OutFmt      *string      `protobuf:"bytes,9,opt,name=outFmt" json:"outFmt,omitempty"`
	Rotation    *int32       `protobuf:"varint,10,opt,name=rotation" json:"rotation,omitempty"`
	Type        *uint32      `protobuf:"varint,11,opt,name=type" json:"type,omitempty"`
	Cdntype     *uint32      `protobuf:"varint,12,opt,name=cdntype" json:"cdntype,omitempty"`
	NewMsgId    *uint64      `protobuf:"varint,13,opt,name=newMsgId" json:"newMsgId,omitempty"`
}

func (x *DownloadAppAttachRequest) Reset() {
	*x = DownloadAppAttachRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DownloadAppAttach_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadAppAttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadAppAttachRequest) ProtoMessage() {}

func (x *DownloadAppAttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DownloadAppAttach_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadAppAttachRequest.ProtoReflect.Descriptor instead.
func (*DownloadAppAttachRequest) Descriptor() ([]byte, []int) {
	return file_DownloadAppAttach_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadAppAttachRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *DownloadAppAttachRequest) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *DownloadAppAttachRequest) GetSdkVersion() uint32 {
	if x != nil && x.SdkVersion != nil {
		return *x.SdkVersion
	}
	return 0
}

func (x *DownloadAppAttachRequest) GetMediaId() string {
	if x != nil && x.MediaId != nil {
		return *x.MediaId
	}
	return ""
}

func (x *DownloadAppAttachRequest) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *DownloadAppAttachRequest) GetTotalLen() uint32 {
	if x != nil && x.TotalLen != nil {
		return *x.TotalLen
	}
	return 0
}

func (x *DownloadAppAttachRequest) GetStartPos() uint32 {
	if x != nil && x.StartPos != nil {
		return *x.StartPos
	}
	return 0
}

func (x *DownloadAppAttachRequest) GetDataLen() uint32 {
	if x != nil && x.DataLen != nil {
		return *x.DataLen
	}
	return 0
}

func (x *DownloadAppAttachRequest) GetOutFmt() string {
	if x != nil && x.OutFmt != nil {
		return *x.OutFmt
	}
	return ""
}

func (x *DownloadAppAttachRequest) GetRotation() int32 {
	if x != nil && x.Rotation != nil {
		return *x.Rotation
	}
	return 0
}

func (x *DownloadAppAttachRequest) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *DownloadAppAttachRequest) GetCdntype() uint32 {
	if x != nil && x.Cdntype != nil {
		return *x.Cdntype
	}
	return 0
}

func (x *DownloadAppAttachRequest) GetNewMsgId() uint64 {
	if x != nil && x.NewMsgId != nil {
		return *x.NewMsgId
	}
	return 0
}

type DownloadAppAttachResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse *BaseResponse     `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
	AppId        *string           `protobuf:"bytes,2,opt,name=appId" json:"appId,omitempty"`
	MediaId      *string           `protobuf:"bytes,3,opt,name=mediaId" json:"mediaId,omitempty"`
	UserName     *string           `protobuf:"bytes,4,opt,name=userName" json:"userName,omitempty"`
	TotalLen     *uint32           `protobuf:"varint,5,req,name=totalLen" json:"totalLen,omitempty"`
	StartPos     *uint32           `protobuf:"varint,6,req,name=startPos" json:"startPos,omitempty"`
	DataLen      *uint32           `protobuf:"varint,7,req,name=dataLen" json:"dataLen,omitempty"`
	Data         *SKBuiltinBufferT `protobuf:"bytes,8,req,name=data" json:"data,omitempty"`
}

func (x *DownloadAppAttachResponse) Reset() {
	*x = DownloadAppAttachResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DownloadAppAttach_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadAppAttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadAppAttachResponse) ProtoMessage() {}

func (x *DownloadAppAttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DownloadAppAttach_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadAppAttachResponse.ProtoReflect.Descriptor instead.
func (*DownloadAppAttachResponse) Descriptor() ([]byte, []int) {
	return file_DownloadAppAttach_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadAppAttachResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *DownloadAppAttachResponse) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *DownloadAppAttachResponse) GetMediaId() string {
	if x != nil && x.MediaId != nil {
		return *x.MediaId
	}
	return ""
}

func (x *DownloadAppAttachResponse) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *DownloadAppAttachResponse) GetTotalLen() uint32 {
	if x != nil && x.TotalLen != nil {
		return *x.TotalLen
	}
	return 0
}

func (x *DownloadAppAttachResponse) GetStartPos() uint32 {
	if x != nil && x.StartPos != nil {
		return *x.StartPos
	}
	return 0
}

func (x *DownloadAppAttachResponse) GetDataLen() uint32 {
	if x != nil && x.DataLen != nil {
		return *x.DataLen
	}
	return 0
}

func (x *DownloadAppAttachResponse) GetData() *SKBuiltinBufferT {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_DownloadAppAttach_proto protoreflect.FileDescriptor

var file_DownloadAppAttach_proto_rawDesc = []byte{
	0x0a, 0x17, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f,
	0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x03,
	0x0a, 0x18, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x64, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x64, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c,
	0x65, 0x6e, 0x18, 0x06, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c,
	0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x18, 0x07,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x02, 0x28, 0x0d, 0x52,
	0x07, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x46,
	0x6d, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x46, 0x6d, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x64, 0x6e, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x63, 0x64, 0x6e, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65,
	0x77, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6e, 0x65,
	0x77, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x94, 0x02, 0x0a, 0x19, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x18,
	0x05, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x02, 0x28,
	0x0d, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x61, 0x74, 0x61, 0x4c, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x07, 0x64, 0x61,
	0x74, 0x61, 0x4c, 0x65, 0x6e, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x42,
	0x75, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_DownloadAppAttach_proto_rawDescOnce sync.Once
	file_DownloadAppAttach_proto_rawDescData = file_DownloadAppAttach_proto_rawDesc
)

func file_DownloadAppAttach_proto_rawDescGZIP() []byte {
	file_DownloadAppAttach_proto_rawDescOnce.Do(func() {
		file_DownloadAppAttach_proto_rawDescData = protoimpl.X.CompressGZIP(file_DownloadAppAttach_proto_rawDescData)
	})
	return file_DownloadAppAttach_proto_rawDescData
}

var file_DownloadAppAttach_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_DownloadAppAttach_proto_goTypes = []interface{}{
	(*DownloadAppAttachRequest)(nil),  // 0: DownloadAppAttachRequest
	(*DownloadAppAttachResponse)(nil), // 1: DownloadAppAttachResponse
	(*BaseRequest)(nil),               // 2: BaseRequest
	(*BaseResponse)(nil),              // 3: BaseResponse
	(*SKBuiltinBufferT)(nil),          // 4: SKBuiltinBuffer_t
}
var file_DownloadAppAttach_proto_depIdxs = []int32{
	2, // 0: DownloadAppAttachRequest.baseRequest:type_name -> BaseRequest
	3, // 1: DownloadAppAttachResponse.baseResponse:type_name -> BaseResponse
	4, // 2: DownloadAppAttachResponse.data:type_name -> SKBuiltinBuffer_t
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_DownloadAppAttach_proto_init() }
func file_DownloadAppAttach_proto_init() {
	if File_DownloadAppAttach_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_DownloadAppAttach_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadAppAttachRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_DownloadAppAttach_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadAppAttachResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DownloadAppAttach_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DownloadAppAttach_proto_goTypes,
		DependencyIndexes: file_DownloadAppAttach_proto_depIdxs,
		MessageInfos:      file_DownloadAppAttach_proto_msgTypes,
	}.Build()
	File_DownloadAppAttach_proto = out.File
	file_DownloadAppAttach_proto_rawDesc = nil
	file_DownloadAppAttach_proto_goTypes = nil
	file_DownloadAppAttach_proto_depIdxs = nil
}
