// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: GetChatroomMemberDetail.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChatroomMemberDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest      *BaseRequest `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	ChatRoomUserName *string      `protobuf:"bytes,2,opt,name=chatRoomUserName" json:"chatRoomUserName,omitempty"`
	ClientVersion    *uint32      `protobuf:"varint,3,req,name=clientVersion" json:"clientVersion,omitempty"`
}

func (x *GetChatroomMemberDetailRequest) Reset() {
	*x = GetChatroomMemberDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetChatroomMemberDetail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatroomMemberDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatroomMemberDetailRequest) ProtoMessage() {}

func (x *GetChatroomMemberDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GetChatroomMemberDetail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatroomMemberDetailRequest.ProtoReflect.Descriptor instead.
func (*GetChatroomMemberDetailRequest) Descriptor() ([]byte, []int) {
	return file_GetChatroomMemberDetail_proto_rawDescGZIP(), []int{0}
}

func (x *GetChatroomMemberDetailRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *GetChatroomMemberDetailRequest) GetChatRoomUserName() string {
	if x != nil && x.ChatRoomUserName != nil {
		return *x.ChatRoomUserName
	}
	return ""
}

func (x *GetChatroomMemberDetailRequest) GetClientVersion() uint32 {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return 0
}

type GetChatroomMemberDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse     *BaseResponse       `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
	ChatRoomUserName *string             `protobuf:"bytes,2,opt,name=chatRoomUserName" json:"chatRoomUserName,omitempty"`
	ServerVersion    *uint32             `protobuf:"varint,3,req,name=serverVersion" json:"serverVersion,omitempty"`
	NewChatroomData  *ChatRoomMemberData `protobuf:"bytes,4,req,name=newChatroomData" json:"newChatroomData,omitempty"`
}

func (x *GetChatroomMemberDetailResponse) Reset() {
	*x = GetChatroomMemberDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetChatroomMemberDetail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatroomMemberDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatroomMemberDetailResponse) ProtoMessage() {}

func (x *GetChatroomMemberDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GetChatroomMemberDetail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatroomMemberDetailResponse.ProtoReflect.Descriptor instead.
func (*GetChatroomMemberDetailResponse) Descriptor() ([]byte, []int) {
	return file_GetChatroomMemberDetail_proto_rawDescGZIP(), []int{1}
}

func (x *GetChatroomMemberDetailResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetChatroomMemberDetailResponse) GetChatRoomUserName() string {
	if x != nil && x.ChatRoomUserName != nil {
		return *x.ChatRoomUserName
	}
	return ""
}

func (x *GetChatroomMemberDetailResponse) GetServerVersion() uint32 {
	if x != nil && x.ServerVersion != nil {
		return *x.ServerVersion
	}
	return 0
}

func (x *GetChatroomMemberDetailResponse) GetNewChatroomData() *ChatRoomMemberData {
	if x != nil {
		return x.NewChatroomData
	}
	return nil
}

var File_GetChatroomMemberDetail_proto protoreflect.FileDescriptor

var file_GetChatroomMemberDetail_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x72,
	0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xe5, 0x01, 0x0a, 0x1f, 0x47, 0x65, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c,
	0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x68, 0x61, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x02,
	0x28, 0x0d, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x3d, 0x0a, 0x0f, 0x6e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x68, 0x61,
	0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x0f, 0x6e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_GetChatroomMemberDetail_proto_rawDescOnce sync.Once
	file_GetChatroomMemberDetail_proto_rawDescData = file_GetChatroomMemberDetail_proto_rawDesc
)

func file_GetChatroomMemberDetail_proto_rawDescGZIP() []byte {
	file_GetChatroomMemberDetail_proto_rawDescOnce.Do(func() {
		file_GetChatroomMemberDetail_proto_rawDescData = protoimpl.X.CompressGZIP(file_GetChatroomMemberDetail_proto_rawDescData)
	})
	return file_GetChatroomMemberDetail_proto_rawDescData
}

var file_GetChatroomMemberDetail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetChatroomMemberDetail_proto_goTypes = []interface{}{
	(*GetChatroomMemberDetailRequest)(nil),  // 0: GetChatroomMemberDetailRequest
	(*GetChatroomMemberDetailResponse)(nil), // 1: GetChatroomMemberDetailResponse
	(*BaseRequest)(nil),                     // 2: BaseRequest
	(*BaseResponse)(nil),                    // 3: BaseResponse
	(*ChatRoomMemberData)(nil),              // 4: ChatRoomMemberData
}
var file_GetChatroomMemberDetail_proto_depIdxs = []int32{
	2, // 0: GetChatroomMemberDetailRequest.baseRequest:type_name -> BaseRequest
	3, // 1: GetChatroomMemberDetailResponse.baseResponse:type_name -> BaseResponse
	4, // 2: GetChatroomMemberDetailResponse.newChatroomData:type_name -> ChatRoomMemberData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_GetChatroomMemberDetail_proto_init() }
func file_GetChatroomMemberDetail_proto_init() {
	if File_GetChatroomMemberDetail_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GetChatroomMemberDetail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatroomMemberDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GetChatroomMemberDetail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatroomMemberDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GetChatroomMemberDetail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetChatroomMemberDetail_proto_goTypes,
		DependencyIndexes: file_GetChatroomMemberDetail_proto_depIdxs,
		MessageInfos:      file_GetChatroomMemberDetail_proto_msgTypes,
	}.Build()
	File_GetChatroomMemberDetail_proto = out.File
	file_GetChatroomMemberDetail_proto_rawDesc = nil
	file_GetChatroomMemberDetail_proto_goTypes = nil
	file_GetChatroomMemberDetail_proto_depIdxs = nil
}
