// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: HeartBeat.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest               *BaseRequest      `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	TimeStamp                 *uint32           `protobuf:"varint,2,req,name=timeStamp" json:"timeStamp,omitempty"`
	KeyBuf                    *SKBuiltinBufferT `protobuf:"bytes,3,opt,name=keyBuf" json:"keyBuf,omitempty"`
	BlueToothBroadCastContent *SKBuiltinBufferT `protobuf:"bytes,4,opt,name=blueToothBroadCastContent" json:"blueToothBroadCastContent,omitempty"`
	Scene                     *uint32           `protobuf:"varint,5,opt,name=scene" json:"scene,omitempty"`
}

func (x *HeartBeatRequest) Reset() {
	*x = HeartBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HeartBeat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatRequest) ProtoMessage() {}

func (x *HeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_HeartBeat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatRequest.ProtoReflect.Descriptor instead.
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_HeartBeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartBeatRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *HeartBeatRequest) GetTimeStamp() uint32 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

func (x *HeartBeatRequest) GetKeyBuf() *SKBuiltinBufferT {
	if x != nil {
		return x.KeyBuf
	}
	return nil
}

func (x *HeartBeatRequest) GetBlueToothBroadCastContent() *SKBuiltinBufferT {
	if x != nil {
		return x.BlueToothBroadCastContent
	}
	return nil
}

func (x *HeartBeatRequest) GetScene() uint32 {
	if x != nil && x.Scene != nil {
		return *x.Scene
	}
	return 0
}

type HeartBeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse              *BaseResponse     `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
	NextTime                  *uint32           `protobuf:"varint,2,req,name=nextTime" json:"nextTime,omitempty"`
	Selector                  *uint32           `protobuf:"varint,3,opt,name=selector" json:"selector,omitempty"`
	BlueToothBroadCastContent *SKBuiltinBufferT `protobuf:"bytes,4,opt,name=blueToothBroadCastContent" json:"blueToothBroadCastContent,omitempty"`
}

func (x *HeartBeatResponse) Reset() {
	*x = HeartBeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HeartBeat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResponse) ProtoMessage() {}

func (x *HeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_HeartBeat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_HeartBeat_proto_rawDescGZIP(), []int{1}
}

func (x *HeartBeatResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *HeartBeatResponse) GetNextTime() uint32 {
	if x != nil && x.NextTime != nil {
		return *x.NextTime
	}
	return 0
}

func (x *HeartBeatResponse) GetSelector() uint32 {
	if x != nil && x.Selector != nil {
		return *x.Selector
	}
	return 0
}

func (x *HeartBeatResponse) GetBlueToothBroadCastContent() *SKBuiltinBufferT {
	if x != nil {
		return x.BlueToothBroadCastContent
	}
	return nil
}

var File_HeartBeat_proto protoreflect.FileDescriptor

var file_HeartBeat_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf4, 0x01, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x42,
	0x75, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69,
	0x6c, 0x74, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x52, 0x06, 0x6b, 0x65,
	0x79, 0x42, 0x75, 0x66, 0x12, 0x50, 0x0a, 0x19, 0x62, 0x6c, 0x75, 0x65, 0x54, 0x6f, 0x6f, 0x74,
	0x68, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c,
	0x74, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x52, 0x19, 0x62, 0x6c, 0x75,
	0x65, 0x54, 0x6f, 0x6f, 0x74, 0x68, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x22, 0xd0, 0x01, 0x0a,
	0x11, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x50, 0x0a,
	0x19, 0x62, 0x6c, 0x75, 0x65, 0x54, 0x6f, 0x6f, 0x74, 0x68, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43,
	0x61, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66,
	0x65, 0x72, 0x5f, 0x74, 0x52, 0x19, 0x62, 0x6c, 0x75, 0x65, 0x54, 0x6f, 0x6f, 0x74, 0x68, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_HeartBeat_proto_rawDescOnce sync.Once
	file_HeartBeat_proto_rawDescData = file_HeartBeat_proto_rawDesc
)

func file_HeartBeat_proto_rawDescGZIP() []byte {
	file_HeartBeat_proto_rawDescOnce.Do(func() {
		file_HeartBeat_proto_rawDescData = protoimpl.X.CompressGZIP(file_HeartBeat_proto_rawDescData)
	})
	return file_HeartBeat_proto_rawDescData
}

var file_HeartBeat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_HeartBeat_proto_goTypes = []interface{}{
	(*HeartBeatRequest)(nil),  // 0: HeartBeatRequest
	(*HeartBeatResponse)(nil), // 1: HeartBeatResponse
	(*BaseRequest)(nil),       // 2: BaseRequest
	(*SKBuiltinBufferT)(nil),  // 3: SKBuiltinBuffer_t
	(*BaseResponse)(nil),      // 4: BaseResponse
}
var file_HeartBeat_proto_depIdxs = []int32{
	2, // 0: HeartBeatRequest.baseRequest:type_name -> BaseRequest
	3, // 1: HeartBeatRequest.keyBuf:type_name -> SKBuiltinBuffer_t
	3, // 2: HeartBeatRequest.blueToothBroadCastContent:type_name -> SKBuiltinBuffer_t
	4, // 3: HeartBeatResponse.baseResponse:type_name -> BaseResponse
	3, // 4: HeartBeatResponse.blueToothBroadCastContent:type_name -> SKBuiltinBuffer_t
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_HeartBeat_proto_init() }
func file_HeartBeat_proto_init() {
	if File_HeartBeat_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_HeartBeat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HeartBeat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_HeartBeat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HeartBeat_proto_goTypes,
		DependencyIndexes: file_HeartBeat_proto_depIdxs,
		MessageInfos:      file_HeartBeat_proto_msgTypes,
	}.Build()
	File_HeartBeat_proto = out.File
	file_HeartBeat_proto_rawDesc = nil
	file_HeartBeat_proto_goTypes = nil
	file_HeartBeat_proto_depIdxs = nil
}
