// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: InitContact.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitContactRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username                  *string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	CurrentWxcontactSeq       *int32  `protobuf:"varint,2,opt,name=currentWxcontactSeq" json:"currentWxcontactSeq,omitempty"`
	CurrentChatRoomContactSeq *int32  `protobuf:"varint,3,opt,name=currentChatRoomContactSeq" json:"currentChatRoomContactSeq,omitempty"`
}

func (x *InitContactRequest) Reset() {
	*x = InitContactRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InitContact_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitContactRequest) ProtoMessage() {}

func (x *InitContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InitContact_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitContactRequest.ProtoReflect.Descriptor instead.
func (*InitContactRequest) Descriptor() ([]byte, []int) {
	return file_InitContact_proto_rawDescGZIP(), []int{0}
}

func (x *InitContactRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *InitContactRequest) GetCurrentWxcontactSeq() int32 {
	if x != nil && x.CurrentWxcontactSeq != nil {
		return *x.CurrentWxcontactSeq
	}
	return 0
}

func (x *InitContactRequest) GetCurrentChatRoomContactSeq() int32 {
	if x != nil && x.CurrentChatRoomContactSeq != nil {
		return *x.CurrentChatRoomContactSeq
	}
	return 0
}

type InitContactResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse              *BaseResponse `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	CurrentWxcontactSeq       *int32        `protobuf:"varint,2,opt,name=currentWxcontactSeq" json:"currentWxcontactSeq,omitempty"`
	CurrentChatRoomContactSeq *int32        `protobuf:"varint,3,opt,name=currentChatRoomContactSeq" json:"currentChatRoomContactSeq,omitempty"`
	CountinueFlag             *int32        `protobuf:"varint,4,opt,name=countinueFlag" json:"countinueFlag,omitempty"`
	ContactUsernameList       []string      `protobuf:"bytes,5,rep,name=contactUsernameList" json:"contactUsernameList,omitempty"`
}

func (x *InitContactResponse) Reset() {
	*x = InitContactResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InitContact_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitContactResponse) ProtoMessage() {}

func (x *InitContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_InitContact_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitContactResponse.ProtoReflect.Descriptor instead.
func (*InitContactResponse) Descriptor() ([]byte, []int) {
	return file_InitContact_proto_rawDescGZIP(), []int{1}
}

func (x *InitContactResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *InitContactResponse) GetCurrentWxcontactSeq() int32 {
	if x != nil && x.CurrentWxcontactSeq != nil {
		return *x.CurrentWxcontactSeq
	}
	return 0
}

func (x *InitContactResponse) GetCurrentChatRoomContactSeq() int32 {
	if x != nil && x.CurrentChatRoomContactSeq != nil {
		return *x.CurrentChatRoomContactSeq
	}
	return 0
}

func (x *InitContactResponse) GetCountinueFlag() int32 {
	if x != nil && x.CountinueFlag != nil {
		return *x.CountinueFlag
	}
	return 0
}

func (x *InitContactResponse) GetContactUsernameList() []string {
	if x != nil {
		return x.ContactUsernameList
	}
	return nil
}

var File_InitContact_proto protoreflect.FileDescriptor

var file_InitContact_proto_rawDesc = []byte{
	0x0a, 0x11, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x12, 0x49, 0x6e, 0x69, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x57, 0x78, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x53, 0x65,
	0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x57, 0x78, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x53, 0x65, 0x71, 0x12, 0x3c, 0x0a, 0x19,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x53, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x19, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x53, 0x65, 0x71, 0x22, 0x90, 0x02, 0x0a, 0x13, 0x49,
	0x6e, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x57, 0x78, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x53, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x13, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x57, 0x78, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x53, 0x65, 0x71, 0x12, 0x3c, 0x0a, 0x19, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x53, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x19, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x53, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e,
	0x75, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x30, 0x0a, 0x13, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_InitContact_proto_rawDescOnce sync.Once
	file_InitContact_proto_rawDescData = file_InitContact_proto_rawDesc
)

func file_InitContact_proto_rawDescGZIP() []byte {
	file_InitContact_proto_rawDescOnce.Do(func() {
		file_InitContact_proto_rawDescData = protoimpl.X.CompressGZIP(file_InitContact_proto_rawDescData)
	})
	return file_InitContact_proto_rawDescData
}

var file_InitContact_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_InitContact_proto_goTypes = []interface{}{
	(*InitContactRequest)(nil),  // 0: InitContactRequest
	(*InitContactResponse)(nil), // 1: InitContactResponse
	(*BaseResponse)(nil),        // 2: BaseResponse
}
var file_InitContact_proto_depIdxs = []int32{
	2, // 0: InitContactResponse.baseResponse:type_name -> BaseResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_InitContact_proto_init() }
func file_InitContact_proto_init() {
	if File_InitContact_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_InitContact_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitContactRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InitContact_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitContactResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_InitContact_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_InitContact_proto_goTypes,
		DependencyIndexes: file_InitContact_proto_depIdxs,
		MessageInfos:      file_InitContact_proto_msgTypes,
	}.Build()
	File_InitContact_proto = out.File
	file_InitContact_proto_rawDesc = nil
	file_InitContact_proto_goTypes = nil
	file_InitContact_proto_depIdxs = nil
}
