// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: InviteChatRoomMember.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InviteChatRoomMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest          *BaseRequest      `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	MemberCount          *uint32           `protobuf:"varint,2,req,name=memberCount" json:"memberCount,omitempty"`
	MemberList           []*MemberReq      `protobuf:"bytes,3,rep,name=memberList" json:"memberList,omitempty"`
	ChatRoomName         *SKBuiltinStringT `protobuf:"bytes,4,req,name=chatRoomName" json:"chatRoomName,omitempty"`
	InviteScene          *uint32           `protobuf:"varint,5,opt,name=inviteScene" json:"inviteScene,omitempty"`
	AccessApprovalTicket *string           `protobuf:"bytes,6,opt,name=accessApprovalTicket" json:"accessApprovalTicket,omitempty"`
	History              *HistoryInfo      `protobuf:"bytes,7,opt,name=history" json:"history,omitempty"`
}

func (x *InviteChatRoomMemberRequest) Reset() {
	*x = InviteChatRoomMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InviteChatRoomMember_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteChatRoomMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteChatRoomMemberRequest) ProtoMessage() {}

func (x *InviteChatRoomMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InviteChatRoomMember_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteChatRoomMemberRequest.ProtoReflect.Descriptor instead.
func (*InviteChatRoomMemberRequest) Descriptor() ([]byte, []int) {
	return file_InviteChatRoomMember_proto_rawDescGZIP(), []int{0}
}

func (x *InviteChatRoomMemberRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *InviteChatRoomMemberRequest) GetMemberCount() uint32 {
	if x != nil && x.MemberCount != nil {
		return *x.MemberCount
	}
	return 0
}

func (x *InviteChatRoomMemberRequest) GetMemberList() []*MemberReq {
	if x != nil {
		return x.MemberList
	}
	return nil
}

func (x *InviteChatRoomMemberRequest) GetChatRoomName() *SKBuiltinStringT {
	if x != nil {
		return x.ChatRoomName
	}
	return nil
}

func (x *InviteChatRoomMemberRequest) GetInviteScene() uint32 {
	if x != nil && x.InviteScene != nil {
		return *x.InviteScene
	}
	return 0
}

func (x *InviteChatRoomMemberRequest) GetAccessApprovalTicket() string {
	if x != nil && x.AccessApprovalTicket != nil {
		return *x.AccessApprovalTicket
	}
	return ""
}

func (x *InviteChatRoomMemberRequest) GetHistory() *HistoryInfo {
	if x != nil {
		return x.History
	}
	return nil
}

type InviteChatRoomMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse *BaseResponse `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
}

func (x *InviteChatRoomMemberResponse) Reset() {
	*x = InviteChatRoomMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InviteChatRoomMember_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteChatRoomMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteChatRoomMemberResponse) ProtoMessage() {}

func (x *InviteChatRoomMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_InviteChatRoomMember_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteChatRoomMemberResponse.ProtoReflect.Descriptor instead.
func (*InviteChatRoomMemberResponse) Descriptor() ([]byte, []int) {
	return file_InviteChatRoomMember_proto_rawDescGZIP(), []int{1}
}

func (x *InviteChatRoomMemberResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

var File_InviteChatRoomMember_proto protoreflect.FileDescriptor

var file_InviteChatRoomMember_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x69,
	0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x13, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x02, 0x0a, 0x1b, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42, 0x75,
	0x69, 0x6c, 0x74, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x52, 0x0c, 0x63,
	0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x32, 0x0a,
	0x14, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x26, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x51, 0x0a, 0x1c, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c,
	0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_InviteChatRoomMember_proto_rawDescOnce sync.Once
	file_InviteChatRoomMember_proto_rawDescData = file_InviteChatRoomMember_proto_rawDesc
)

func file_InviteChatRoomMember_proto_rawDescGZIP() []byte {
	file_InviteChatRoomMember_proto_rawDescOnce.Do(func() {
		file_InviteChatRoomMember_proto_rawDescData = protoimpl.X.CompressGZIP(file_InviteChatRoomMember_proto_rawDescData)
	})
	return file_InviteChatRoomMember_proto_rawDescData
}

var file_InviteChatRoomMember_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_InviteChatRoomMember_proto_goTypes = []interface{}{
	(*InviteChatRoomMemberRequest)(nil),  // 0: InviteChatRoomMemberRequest
	(*InviteChatRoomMemberResponse)(nil), // 1: InviteChatRoomMemberResponse
	(*BaseRequest)(nil),                  // 2: BaseRequest
	(*MemberReq)(nil),                    // 3: MemberReq
	(*SKBuiltinStringT)(nil),             // 4: SKBuiltinString_t
	(*HistoryInfo)(nil),                  // 5: HistoryInfo
	(*BaseResponse)(nil),                 // 6: BaseResponse
}
var file_InviteChatRoomMember_proto_depIdxs = []int32{
	2, // 0: InviteChatRoomMemberRequest.baseRequest:type_name -> BaseRequest
	3, // 1: InviteChatRoomMemberRequest.memberList:type_name -> MemberReq
	4, // 2: InviteChatRoomMemberRequest.chatRoomName:type_name -> SKBuiltinString_t
	5, // 3: InviteChatRoomMemberRequest.history:type_name -> HistoryInfo
	6, // 4: InviteChatRoomMemberResponse.baseResponse:type_name -> BaseResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_InviteChatRoomMember_proto_init() }
func file_InviteChatRoomMember_proto_init() {
	if File_InviteChatRoomMember_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	file_MicroRoomBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_InviteChatRoomMember_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteChatRoomMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InviteChatRoomMember_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteChatRoomMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_InviteChatRoomMember_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_InviteChatRoomMember_proto_goTypes,
		DependencyIndexes: file_InviteChatRoomMember_proto_depIdxs,
		MessageInfos:      file_InviteChatRoomMember_proto_msgTypes,
	}.Build()
	File_InviteChatRoomMember_proto = out.File
	file_InviteChatRoomMember_proto_rawDesc = nil
	file_InviteChatRoomMember_proto_goTypes = nil
	file_InviteChatRoomMember_proto_depIdxs = nil
}
