// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: ModMsg.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModMsgStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId        *int32            `protobuf:"varint,1,req,name=msgId" json:"msgId,omitempty"`
	FromUserName *SKBuiltinStringT `protobuf:"bytes,2,req,name=fromUserName" json:"fromUserName,omitempty"`
	ToUserName   *SKBuiltinStringT `protobuf:"bytes,3,req,name=toUserName" json:"toUserName,omitempty"`
	Status       *uint32           `protobuf:"varint,4,req,name=status" json:"status,omitempty"`
	NewMsgId     *int64            `protobuf:"varint,5,opt,name=newMsgId" json:"newMsgId,omitempty"`
}

func (x *ModMsgStatus) Reset() {
	*x = ModMsgStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ModMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModMsgStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModMsgStatus) ProtoMessage() {}

func (x *ModMsgStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ModMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModMsgStatus.ProtoReflect.Descriptor instead.
func (*ModMsgStatus) Descriptor() ([]byte, []int) {
	return file_ModMsg_proto_rawDescGZIP(), []int{0}
}

func (x *ModMsgStatus) GetMsgId() int32 {
	if x != nil && x.MsgId != nil {
		return *x.MsgId
	}
	return 0
}

func (x *ModMsgStatus) GetFromUserName() *SKBuiltinStringT {
	if x != nil {
		return x.FromUserName
	}
	return nil
}

func (x *ModMsgStatus) GetToUserName() *SKBuiltinStringT {
	if x != nil {
		return x.ToUserName
	}
	return nil
}

func (x *ModMsgStatus) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *ModMsgStatus) GetNewMsgId() int64 {
	if x != nil && x.NewMsgId != nil {
		return *x.NewMsgId
	}
	return 0
}

type DelContactMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName *SKBuiltinStringT `protobuf:"bytes,1,req,name=userName" json:"userName,omitempty"`
	MaxMsgId *int32            `protobuf:"varint,2,req,name=maxMsgId" json:"maxMsgId,omitempty"`
	NewMsgId *int64            `protobuf:"varint,3,opt,name=newMsgId" json:"newMsgId,omitempty"`
}

func (x *DelContactMsg) Reset() {
	*x = DelContactMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ModMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelContactMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelContactMsg) ProtoMessage() {}

func (x *DelContactMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ModMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelContactMsg.ProtoReflect.Descriptor instead.
func (*DelContactMsg) Descriptor() ([]byte, []int) {
	return file_ModMsg_proto_rawDescGZIP(), []int{1}
}

func (x *DelContactMsg) GetUserName() *SKBuiltinStringT {
	if x != nil {
		return x.UserName
	}
	return nil
}

func (x *DelContactMsg) GetMaxMsgId() int32 {
	if x != nil && x.MaxMsgId != nil {
		return *x.MaxMsgId
	}
	return 0
}

func (x *DelContactMsg) GetNewMsgId() int64 {
	if x != nil && x.NewMsgId != nil {
		return *x.NewMsgId
	}
	return 0
}

type DelMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName  *SKBuiltinStringT `protobuf:"bytes,1,req,name=userName" json:"userName,omitempty"`
	Count     *uint32           `protobuf:"varint,2,req,name=count" json:"count,omitempty"`
	MsgIdList []int32           `protobuf:"varint,3,rep,packed,name=msgIdList" json:"msgIdList,omitempty"`
}

func (x *DelMsg) Reset() {
	*x = DelMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ModMsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMsg) ProtoMessage() {}

func (x *DelMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ModMsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMsg.ProtoReflect.Descriptor instead.
func (*DelMsg) Descriptor() ([]byte, []int) {
	return file_ModMsg_proto_rawDescGZIP(), []int{2}
}

func (x *DelMsg) GetUserName() *SKBuiltinStringT {
	if x != nil {
		return x.UserName
	}
	return nil
}

func (x *DelMsg) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *DelMsg) GetMsgIdList() []int32 {
	if x != nil {
		return x.MsgIdList
	}
	return nil
}

type NewDelMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUserName *string `protobuf:"bytes,1,opt,name=fromUserName" json:"fromUserName,omitempty"`
	ToUserName   *string `protobuf:"bytes,2,opt,name=toUserName" json:"toUserName,omitempty"`
	MsgId        *int32  `protobuf:"varint,3,req,name=msgId" json:"msgId,omitempty"`
	MsgType      *uint32 `protobuf:"varint,4,req,name=msgType" json:"msgType,omitempty"`
	NewMsgId     *int64  `protobuf:"varint,5,opt,name=newMsgId" json:"newMsgId,omitempty"`
}

func (x *NewDelMsg) Reset() {
	*x = NewDelMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ModMsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDelMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDelMsg) ProtoMessage() {}

func (x *NewDelMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ModMsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDelMsg.ProtoReflect.Descriptor instead.
func (*NewDelMsg) Descriptor() ([]byte, []int) {
	return file_ModMsg_proto_rawDescGZIP(), []int{3}
}

func (x *NewDelMsg) GetFromUserName() string {
	if x != nil && x.FromUserName != nil {
		return *x.FromUserName
	}
	return ""
}

func (x *NewDelMsg) GetToUserName() string {
	if x != nil && x.ToUserName != nil {
		return *x.ToUserName
	}
	return ""
}

func (x *NewDelMsg) GetMsgId() int32 {
	if x != nil && x.MsgId != nil {
		return *x.MsgId
	}
	return 0
}

func (x *NewDelMsg) GetMsgType() uint32 {
	if x != nil && x.MsgType != nil {
		return *x.MsgType
	}
	return 0
}

func (x *NewDelMsg) GetNewMsgId() int64 {
	if x != nil && x.NewMsgId != nil {
		return *x.NewMsgId
	}
	return 0
}

var File_ModMsg_proto protoreflect.FileDescriptor

var file_ModMsg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12,
	0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xc4, 0x01, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x05, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x0c, 0x66, 0x72, 0x6f,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x5f, 0x74, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x32, 0x0a, 0x0a, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69,
	0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x52, 0x0a, 0x74, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x65, 0x77, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x6e, 0x65, 0x77, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x77, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x2e, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53,
	0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x74,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61,
	0x78, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61,
	0x78, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x4d, 0x73, 0x67,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x4d, 0x73, 0x67,
	0x49, 0x64, 0x22, 0x70, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x4d, 0x73, 0x67, 0x12, 0x2e, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x5f, 0x74, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x20, 0x0a, 0x09, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x05, 0x42, 0x02, 0x10, 0x01, 0x52, 0x09, 0x6d, 0x73, 0x67, 0x49, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x9b, 0x01, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x44, 0x65, 0x6c, 0x4d,
	0x73, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x55, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x07, 0x6d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x4d, 0x73, 0x67,
	0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x4d, 0x73, 0x67,
	0x49, 0x64, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_ModMsg_proto_rawDescOnce sync.Once
	file_ModMsg_proto_rawDescData = file_ModMsg_proto_rawDesc
)

func file_ModMsg_proto_rawDescGZIP() []byte {
	file_ModMsg_proto_rawDescOnce.Do(func() {
		file_ModMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_ModMsg_proto_rawDescData)
	})
	return file_ModMsg_proto_rawDescData
}

var file_ModMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ModMsg_proto_goTypes = []interface{}{
	(*ModMsgStatus)(nil),     // 0: ModMsgStatus
	(*DelContactMsg)(nil),    // 1: DelContactMsg
	(*DelMsg)(nil),           // 2: DelMsg
	(*NewDelMsg)(nil),        // 3: NewDelMsg
	(*SKBuiltinStringT)(nil), // 4: SKBuiltinString_t
}
var file_ModMsg_proto_depIdxs = []int32{
	4, // 0: ModMsgStatus.fromUserName:type_name -> SKBuiltinString_t
	4, // 1: ModMsgStatus.toUserName:type_name -> SKBuiltinString_t
	4, // 2: DelContactMsg.userName:type_name -> SKBuiltinString_t
	4, // 3: DelMsg.userName:type_name -> SKBuiltinString_t
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ModMsg_proto_init() }
func file_ModMsg_proto_init() {
	if File_ModMsg_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ModMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModMsgStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ModMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelContactMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ModMsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ModMsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDelMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ModMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ModMsg_proto_goTypes,
		DependencyIndexes: file_ModMsg_proto_depIdxs,
		MessageInfos:      file_ModMsg_proto_msgTypes,
	}.Build()
	File_ModMsg_proto = out.File
	file_ModMsg_proto_rawDesc = nil
	file_ModMsg_proto_goTypes = nil
	file_ModMsg_proto_depIdxs = nil
}
