// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: NewSync.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewSyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oplog         *CmdList          `protobuf:"bytes,1,req,name=oplog" json:"oplog,omitempty"`
	Selector      *uint32           `protobuf:"varint,2,req,name=selector" json:"selector,omitempty"`
	KeyBuf        *SKBuiltinBufferT `protobuf:"bytes,3,req,name=keyBuf" json:"keyBuf,omitempty"`
	Scene         *uint32           `protobuf:"varint,4,opt,name=scene" json:"scene,omitempty"`
	DeviceType    *string           `protobuf:"bytes,5,opt,name=deviceType" json:"deviceType,omitempty"`
	NetworkType   *uint32           `protobuf:"varint,6,opt,name=networkType" json:"networkType,omitempty"`     // 3
	SyncMsgDigest *uint32           `protobuf:"varint,7,opt,name=syncMsgDigest" json:"syncMsgDigest,omitempty"` // 1 short link , 0 long link
}

func (x *NewSyncRequest) Reset() {
	*x = NewSyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NewSync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSyncRequest) ProtoMessage() {}

func (x *NewSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_NewSync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSyncRequest.ProtoReflect.Descriptor instead.
func (*NewSyncRequest) Descriptor() ([]byte, []int) {
	return file_NewSync_proto_rawDescGZIP(), []int{0}
}

func (x *NewSyncRequest) GetOplog() *CmdList {
	if x != nil {
		return x.Oplog
	}
	return nil
}

func (x *NewSyncRequest) GetSelector() uint32 {
	if x != nil && x.Selector != nil {
		return *x.Selector
	}
	return 0
}

func (x *NewSyncRequest) GetKeyBuf() *SKBuiltinBufferT {
	if x != nil {
		return x.KeyBuf
	}
	return nil
}

func (x *NewSyncRequest) GetScene() uint32 {
	if x != nil && x.Scene != nil {
		return *x.Scene
	}
	return 0
}

func (x *NewSyncRequest) GetDeviceType() string {
	if x != nil && x.DeviceType != nil {
		return *x.DeviceType
	}
	return ""
}

func (x *NewSyncRequest) GetNetworkType() uint32 {
	if x != nil && x.NetworkType != nil {
		return *x.NetworkType
	}
	return 0
}

func (x *NewSyncRequest) GetSyncMsgDigest() uint32 {
	if x != nil && x.SyncMsgDigest != nil {
		return *x.SyncMsgDigest
	}
	return 0
}

type NewSyncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret           *int32            `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	CmdList       *CmdList          `protobuf:"bytes,2,req,name=cmdList" json:"cmdList,omitempty"`
	ContinueFlag  *uint32           `protobuf:"varint,3,req,name=continueFlag" json:"continueFlag,omitempty"`
	KeyBuf        *SKBuiltinBufferT `protobuf:"bytes,4,req,name=keyBuf" json:"keyBuf,omitempty"`
	Status        *uint32           `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
	OnlineVersion *uint32           `protobuf:"varint,6,opt,name=onlineVersion" json:"onlineVersion,omitempty"`
	ServerTime    *uint32           `protobuf:"varint,7,opt,name=serverTime" json:"serverTime,omitempty"`
}

func (x *NewSyncResponse) Reset() {
	*x = NewSyncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NewSync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSyncResponse) ProtoMessage() {}

func (x *NewSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_NewSync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSyncResponse.ProtoReflect.Descriptor instead.
func (*NewSyncResponse) Descriptor() ([]byte, []int) {
	return file_NewSync_proto_rawDescGZIP(), []int{1}
}

func (x *NewSyncResponse) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *NewSyncResponse) GetCmdList() *CmdList {
	if x != nil {
		return x.CmdList
	}
	return nil
}

func (x *NewSyncResponse) GetContinueFlag() uint32 {
	if x != nil && x.ContinueFlag != nil {
		return *x.ContinueFlag
	}
	return 0
}

func (x *NewSyncResponse) GetKeyBuf() *SKBuiltinBufferT {
	if x != nil {
		return x.KeyBuf
	}
	return nil
}

func (x *NewSyncResponse) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *NewSyncResponse) GetOnlineVersion() uint32 {
	if x != nil && x.OnlineVersion != nil {
		return *x.OnlineVersion
	}
	return 0
}

func (x *NewSyncResponse) GetServerTime() uint32 {
	if x != nil && x.ServerTime != nil {
		return *x.ServerTime
	}
	return 0
}

var File_NewSync_proto protoreflect.FileDescriptor

var file_NewSync_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x4e, 0x65, 0x77, 0x53, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xf6, 0x01, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x53, 0x79, 0x6e, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x05, 0x6f, 0x70, 0x6c, 0x6f, 0x67, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x6d, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x05, 0x6f, 0x70, 0x6c, 0x6f, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x42, 0x75, 0x66, 0x18, 0x03, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x42, 0x75,
	0x66, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x42, 0x75, 0x66, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x79, 0x6e, 0x63, 0x4d, 0x73,
	0x67, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x73,
	0x79, 0x6e, 0x63, 0x4d, 0x73, 0x67, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0xf5, 0x01, 0x0a,
	0x0f, 0x4e, 0x65, 0x77, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x72,
	0x65, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x63, 0x6d, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x6d, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x07, 0x63,
	0x6d, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e,
	0x75, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6f,
	0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x2a, 0x0a, 0x06, 0x6b, 0x65,
	0x79, 0x42, 0x75, 0x66, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42,
	0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x52, 0x06,
	0x6b, 0x65, 0x79, 0x42, 0x75, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24,
	0x0a, 0x0d, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x54, 0x69, 0x6d, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d,
	0x73, 0x67,
}

var (
	file_NewSync_proto_rawDescOnce sync.Once
	file_NewSync_proto_rawDescData = file_NewSync_proto_rawDesc
)

func file_NewSync_proto_rawDescGZIP() []byte {
	file_NewSync_proto_rawDescOnce.Do(func() {
		file_NewSync_proto_rawDescData = protoimpl.X.CompressGZIP(file_NewSync_proto_rawDescData)
	})
	return file_NewSync_proto_rawDescData
}

var file_NewSync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_NewSync_proto_goTypes = []interface{}{
	(*NewSyncRequest)(nil),   // 0: NewSyncRequest
	(*NewSyncResponse)(nil),  // 1: NewSyncResponse
	(*CmdList)(nil),          // 2: CmdList
	(*SKBuiltinBufferT)(nil), // 3: SKBuiltinBuffer_t
}
var file_NewSync_proto_depIdxs = []int32{
	2, // 0: NewSyncRequest.oplog:type_name -> CmdList
	3, // 1: NewSyncRequest.keyBuf:type_name -> SKBuiltinBuffer_t
	2, // 2: NewSyncResponse.cmdList:type_name -> CmdList
	3, // 3: NewSyncResponse.keyBuf:type_name -> SKBuiltinBuffer_t
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_NewSync_proto_init() }
func file_NewSync_proto_init() {
	if File_NewSync_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_NewSync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewSyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NewSync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewSyncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_NewSync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_NewSync_proto_goTypes,
		DependencyIndexes: file_NewSync_proto_depIdxs,
		MessageInfos:      file_NewSync_proto_msgTypes,
	}.Build()
	File_NewSync_proto = out.File
	file_NewSync_proto_rawDesc = nil
	file_NewSync_proto_goTypes = nil
	file_NewSync_proto_depIdxs = nil
}
