// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: Oplog.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OplogRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count *uint32 `protobuf:"varint,1,req,name=count" json:"count,omitempty"`
	Ret   []int32 `protobuf:"varint,2,rep,packed,name=ret" json:"ret,omitempty"`
}

func (x *OplogRet) Reset() {
	*x = OplogRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Oplog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OplogRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OplogRet) ProtoMessage() {}

func (x *OplogRet) ProtoReflect() protoreflect.Message {
	mi := &file_Oplog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OplogRet.ProtoReflect.Descriptor instead.
func (*OplogRet) Descriptor() ([]byte, []int) {
	return file_Oplog_proto_rawDescGZIP(), []int{0}
}

func (x *OplogRet) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *OplogRet) GetRet() []int32 {
	if x != nil {
		return x.Ret
	}
	return nil
}

type OplogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oplog *CmdList `protobuf:"bytes,1,req,name=oplog" json:"oplog,omitempty"`
}

func (x *OplogRequest) Reset() {
	*x = OplogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Oplog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OplogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OplogRequest) ProtoMessage() {}

func (x *OplogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Oplog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OplogRequest.ProtoReflect.Descriptor instead.
func (*OplogRequest) Descriptor() ([]byte, []int) {
	return file_Oplog_proto_rawDescGZIP(), []int{1}
}

func (x *OplogRequest) GetOplog() *CmdList {
	if x != nil {
		return x.Oplog
	}
	return nil
}

type OplogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      *int32    `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	OplogRet *OplogRet `protobuf:"bytes,2,req,name=oplogRet" json:"oplogRet,omitempty"`
}

func (x *OplogResponse) Reset() {
	*x = OplogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Oplog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OplogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OplogResponse) ProtoMessage() {}

func (x *OplogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Oplog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OplogResponse.ProtoReflect.Descriptor instead.
func (*OplogResponse) Descriptor() ([]byte, []int) {
	return file_Oplog_proto_rawDescGZIP(), []int{2}
}

func (x *OplogResponse) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *OplogResponse) GetOplogRet() *OplogRet {
	if x != nil {
		return x.OplogRet
	}
	return nil
}

var File_Oplog_proto protoreflect.FileDescriptor

var file_Oplog_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x4f, 0x70, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d,
	0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x36, 0x0a, 0x08, 0x4f, 0x70, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05,
	0x42, 0x02, 0x10, 0x01, 0x52, 0x03, 0x72, 0x65, 0x74, 0x22, 0x2e, 0x0a, 0x0c, 0x4f, 0x70, 0x6c,
	0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x05, 0x6f, 0x70, 0x6c,
	0x6f, 0x67, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x6d, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x05, 0x6f, 0x70, 0x6c, 0x6f, 0x67, 0x22, 0x48, 0x0a, 0x0d, 0x4f, 0x70, 0x6c,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x25, 0x0a, 0x08,
	0x6f, 0x70, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x4f, 0x70, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x74, 0x52, 0x08, 0x6f, 0x70, 0x6c, 0x6f, 0x67,
	0x52, 0x65, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73,
	0x67,
}

var (
	file_Oplog_proto_rawDescOnce sync.Once
	file_Oplog_proto_rawDescData = file_Oplog_proto_rawDesc
)

func file_Oplog_proto_rawDescGZIP() []byte {
	file_Oplog_proto_rawDescOnce.Do(func() {
		file_Oplog_proto_rawDescData = protoimpl.X.CompressGZIP(file_Oplog_proto_rawDescData)
	})
	return file_Oplog_proto_rawDescData
}

var file_Oplog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Oplog_proto_goTypes = []interface{}{
	(*OplogRet)(nil),      // 0: OplogRet
	(*OplogRequest)(nil),  // 1: OplogRequest
	(*OplogResponse)(nil), // 2: OplogResponse
	(*CmdList)(nil),       // 3: CmdList
}
var file_Oplog_proto_depIdxs = []int32{
	3, // 0: OplogRequest.oplog:type_name -> CmdList
	0, // 1: OplogResponse.oplogRet:type_name -> OplogRet
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Oplog_proto_init() }
func file_Oplog_proto_init() {
	if File_Oplog_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Oplog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OplogRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Oplog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OplogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Oplog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OplogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Oplog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Oplog_proto_goTypes,
		DependencyIndexes: file_Oplog_proto_depIdxs,
		MessageInfos:      file_Oplog_proto_msgTypes,
	}.Build()
	File_Oplog_proto = out.File
	file_Oplog_proto_rawDesc = nil
	file_Oplog_proto_goTypes = nil
	file_Oplog_proto_depIdxs = nil
}
