// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: PcFinder.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type H5AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest *BaseRequest      `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	H5Version   *uint32           `protobuf:"varint,2,opt,name=h5Version" json:"h5Version,omitempty"`
	H5Domain    *string           `protobuf:"bytes,3,opt,name=h5Domain" json:"h5Domain,omitempty"`
	Ccdata      *SKBuiltinBufferT `protobuf:"bytes,4,opt,name=ccdata" json:"ccdata,omitempty"`
	Scope       *string           `protobuf:"bytes,5,opt,name=scope" json:"scope,omitempty"`
}

func (x *H5AuthRequest) Reset() {
	*x = H5AuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PcFinder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *H5AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H5AuthRequest) ProtoMessage() {}

func (x *H5AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PcFinder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H5AuthRequest.ProtoReflect.Descriptor instead.
func (*H5AuthRequest) Descriptor() ([]byte, []int) {
	return file_PcFinder_proto_rawDescGZIP(), []int{0}
}

func (x *H5AuthRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *H5AuthRequest) GetH5Version() uint32 {
	if x != nil && x.H5Version != nil {
		return *x.H5Version
	}
	return 0
}

func (x *H5AuthRequest) GetH5Domain() string {
	if x != nil && x.H5Domain != nil {
		return *x.H5Domain
	}
	return ""
}

func (x *H5AuthRequest) GetCcdata() *SKBuiltinBufferT {
	if x != nil {
		return x.Ccdata
	}
	return nil
}

func (x *H5AuthRequest) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

type H5AuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse *BaseResponse `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	H5Authtoken  *string       `protobuf:"bytes,2,opt,name=h5Authtoken" json:"h5Authtoken,omitempty"`
}

func (x *H5AuthResponse) Reset() {
	*x = H5AuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PcFinder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *H5AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H5AuthResponse) ProtoMessage() {}

func (x *H5AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PcFinder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H5AuthResponse.ProtoReflect.Descriptor instead.
func (*H5AuthResponse) Descriptor() ([]byte, []int) {
	return file_PcFinder_proto_rawDescGZIP(), []int{1}
}

func (x *H5AuthResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *H5AuthResponse) GetH5Authtoken() string {
	if x != nil && x.H5Authtoken != nil {
		return *x.H5Authtoken
	}
	return ""
}

type TransferJsApiHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (x *TransferJsApiHeader) Reset() {
	*x = TransferJsApiHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PcFinder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferJsApiHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferJsApiHeader) ProtoMessage() {}

func (x *TransferJsApiHeader) ProtoReflect() protoreflect.Message {
	mi := &file_PcFinder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferJsApiHeader.ProtoReflect.Descriptor instead.
func (*TransferJsApiHeader) Descriptor() ([]byte, []int) {
	return file_PcFinder_proto_rawDescGZIP(), []int{2}
}

func (x *TransferJsApiHeader) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *TransferJsApiHeader) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type JsApiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      *int32                 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	ErrorMsg *string                `protobuf:"bytes,2,opt,name=errorMsg" json:"errorMsg,omitempty"`
	RespJson *string                `protobuf:"bytes,3,opt,name=respJson" json:"respJson,omitempty"`
	Header   []*TransferJsApiHeader `protobuf:"bytes,4,rep,name=header" json:"header,omitempty"`
}

func (x *JsApiResponse) Reset() {
	*x = JsApiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PcFinder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsApiResponse) ProtoMessage() {}

func (x *JsApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PcFinder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsApiResponse.ProtoReflect.Descriptor instead.
func (*JsApiResponse) Descriptor() ([]byte, []int) {
	return file_PcFinder_proto_rawDescGZIP(), []int{3}
}

func (x *JsApiResponse) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *JsApiResponse) GetErrorMsg() string {
	if x != nil && x.ErrorMsg != nil {
		return *x.ErrorMsg
	}
	return ""
}

func (x *JsApiResponse) GetRespJson() string {
	if x != nil && x.RespJson != nil {
		return *x.RespJson
	}
	return ""
}

func (x *JsApiResponse) GetHeader() []*TransferJsApiHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type JsApiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      *string                `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	ReqJson  *string                `protobuf:"bytes,2,opt,name=reqJson" json:"reqJson,omitempty"`
	CgiCmdid *uint32                `protobuf:"varint,3,opt,name=cgiCmdid" json:"cgiCmdid,omitempty"`
	Header   []*TransferJsApiHeader `protobuf:"bytes,4,rep,name=header" json:"header,omitempty"`
	Method   *uint32                `protobuf:"varint,5,opt,name=method" json:"method,omitempty"`
}

func (x *JsApiRequest) Reset() {
	*x = JsApiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PcFinder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsApiRequest) ProtoMessage() {}

func (x *JsApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PcFinder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsApiRequest.ProtoReflect.Descriptor instead.
func (*JsApiRequest) Descriptor() ([]byte, []int) {
	return file_PcFinder_proto_rawDescGZIP(), []int{4}
}

func (x *JsApiRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *JsApiRequest) GetReqJson() string {
	if x != nil && x.ReqJson != nil {
		return *x.ReqJson
	}
	return ""
}

func (x *JsApiRequest) GetCgiCmdid() uint32 {
	if x != nil && x.CgiCmdid != nil {
		return *x.CgiCmdid
	}
	return 0
}

func (x *JsApiRequest) GetHeader() []*TransferJsApiHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *JsApiRequest) GetMethod() uint32 {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return 0
}

type H5ExtTransferRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest            *BaseRequest      `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	JsApiRequest           *JsApiRequest     `protobuf:"bytes,2,opt,name=jsApiRequest" json:"jsApiRequest,omitempty"`
	H5Authtoken            *string           `protobuf:"bytes,3,opt,name=h5Authtoken" json:"h5Authtoken,omitempty"`
	ClientCheckData        *SKBuiltinBufferT `protobuf:"bytes,4,opt,name=clientCheckData" json:"clientCheckData,omitempty"`
	H5Url                  *string           `protobuf:"bytes,5,opt,name=h5Url" json:"h5Url,omitempty"`
	JsApiControlBytesIndex *uint32           `protobuf:"varint,6,opt,name=jsApiControlBytesIndex" json:"jsApiControlBytesIndex,omitempty"`
	Scope                  *string           `protobuf:"bytes,7,opt,name=scope" json:"scope,omitempty"`
}

func (x *H5ExtTransferRequest) Reset() {
	*x = H5ExtTransferRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PcFinder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *H5ExtTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H5ExtTransferRequest) ProtoMessage() {}

func (x *H5ExtTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PcFinder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H5ExtTransferRequest.ProtoReflect.Descriptor instead.
func (*H5ExtTransferRequest) Descriptor() ([]byte, []int) {
	return file_PcFinder_proto_rawDescGZIP(), []int{5}
}

func (x *H5ExtTransferRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *H5ExtTransferRequest) GetJsApiRequest() *JsApiRequest {
	if x != nil {
		return x.JsApiRequest
	}
	return nil
}

func (x *H5ExtTransferRequest) GetH5Authtoken() string {
	if x != nil && x.H5Authtoken != nil {
		return *x.H5Authtoken
	}
	return ""
}

func (x *H5ExtTransferRequest) GetClientCheckData() *SKBuiltinBufferT {
	if x != nil {
		return x.ClientCheckData
	}
	return nil
}

func (x *H5ExtTransferRequest) GetH5Url() string {
	if x != nil && x.H5Url != nil {
		return *x.H5Url
	}
	return ""
}

func (x *H5ExtTransferRequest) GetJsApiControlBytesIndex() uint32 {
	if x != nil && x.JsApiControlBytesIndex != nil {
		return *x.JsApiControlBytesIndex
	}
	return 0
}

func (x *H5ExtTransferRequest) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

type H5ExtTransferResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse  *BaseResponse  `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	JsApiResponse *JsApiResponse `protobuf:"bytes,2,opt,name=jsApiResponse" json:"jsApiResponse,omitempty"`
}

func (x *H5ExtTransferResponse) Reset() {
	*x = H5ExtTransferResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PcFinder_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *H5ExtTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H5ExtTransferResponse) ProtoMessage() {}

func (x *H5ExtTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PcFinder_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H5ExtTransferResponse.ProtoReflect.Descriptor instead.
func (*H5ExtTransferResponse) Descriptor() ([]byte, []int) {
	return file_PcFinder_proto_rawDescGZIP(), []int{6}
}

func (x *H5ExtTransferResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *H5ExtTransferResponse) GetJsApiResponse() *JsApiResponse {
	if x != nil {
		return x.JsApiResponse
	}
	return nil
}

var File_PcFinder_proto protoreflect.FileDescriptor

var file_PcFinder_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x50, 0x63, 0x46, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x01, 0x0a, 0x0d, 0x48, 0x35, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x35, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x68, 0x35, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x35, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x35, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x12, 0x2a, 0x0a, 0x06, 0x63, 0x63, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66,
	0x65, 0x72, 0x5f, 0x74, 0x52, 0x06, 0x63, 0x63, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x6f,
	0x70, 0x65, 0x22, 0x65, 0x0a, 0x0e, 0x48, 0x35, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x35, 0x41, 0x75, 0x74,
	0x68, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x35,
	0x41, 0x75, 0x74, 0x68, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3d, 0x0a, 0x13, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x4a, 0x73, 0x41, 0x70, 0x69, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x0d, 0x4a, 0x73, 0x41,
	0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x4a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4a,
	0x73, 0x41, 0x70, 0x69, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x22, 0x9c, 0x01, 0x0a, 0x0c, 0x4a, 0x73, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x4a, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x4a, 0x73, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x67, 0x69, 0x43, 0x6d, 0x64, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x63, 0x67, 0x69, 0x43, 0x6d, 0x64, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4a, 0x73, 0x41, 0x70, 0x69, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x22, 0xbd, 0x02, 0x0a, 0x14, 0x48, 0x35, 0x45, 0x78, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x0c, 0x6a, 0x73,
	0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x4a, 0x73, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x0c, 0x6a, 0x73, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x68, 0x35, 0x41, 0x75, 0x74, 0x68, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x68, 0x35, 0x41, 0x75, 0x74, 0x68, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x3c, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69,
	0x6c, 0x74, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x52, 0x0f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x68, 0x35, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x35,
	0x55, 0x72, 0x6c, 0x12, 0x36, 0x0a, 0x16, 0x6a, 0x73, 0x41, 0x70, 0x69, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x16, 0x6a, 0x73, 0x41, 0x70, 0x69, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x6f, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70,
	0x65, 0x22, 0x80, 0x01, 0x0a, 0x15, 0x48, 0x35, 0x45, 0x78, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x62,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x0d, 0x6a, 0x73, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4a, 0x73, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0d, 0x6a, 0x73, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d,
	0x73, 0x67,
}

var (
	file_PcFinder_proto_rawDescOnce sync.Once
	file_PcFinder_proto_rawDescData = file_PcFinder_proto_rawDesc
)

func file_PcFinder_proto_rawDescGZIP() []byte {
	file_PcFinder_proto_rawDescOnce.Do(func() {
		file_PcFinder_proto_rawDescData = protoimpl.X.CompressGZIP(file_PcFinder_proto_rawDescData)
	})
	return file_PcFinder_proto_rawDescData
}

var file_PcFinder_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_PcFinder_proto_goTypes = []interface{}{
	(*H5AuthRequest)(nil),         // 0: H5AuthRequest
	(*H5AuthResponse)(nil),        // 1: H5AuthResponse
	(*TransferJsApiHeader)(nil),   // 2: TransferJsApiHeader
	(*JsApiResponse)(nil),         // 3: JsApiResponse
	(*JsApiRequest)(nil),          // 4: JsApiRequest
	(*H5ExtTransferRequest)(nil),  // 5: H5ExtTransferRequest
	(*H5ExtTransferResponse)(nil), // 6: H5ExtTransferResponse
	(*BaseRequest)(nil),           // 7: BaseRequest
	(*SKBuiltinBufferT)(nil),      // 8: SKBuiltinBuffer_t
	(*BaseResponse)(nil),          // 9: BaseResponse
}
var file_PcFinder_proto_depIdxs = []int32{
	7,  // 0: H5AuthRequest.baseRequest:type_name -> BaseRequest
	8,  // 1: H5AuthRequest.ccdata:type_name -> SKBuiltinBuffer_t
	9,  // 2: H5AuthResponse.baseResponse:type_name -> BaseResponse
	2,  // 3: JsApiResponse.header:type_name -> TransferJsApiHeader
	2,  // 4: JsApiRequest.header:type_name -> TransferJsApiHeader
	7,  // 5: H5ExtTransferRequest.baseRequest:type_name -> BaseRequest
	4,  // 6: H5ExtTransferRequest.jsApiRequest:type_name -> JsApiRequest
	8,  // 7: H5ExtTransferRequest.clientCheckData:type_name -> SKBuiltinBuffer_t
	9,  // 8: H5ExtTransferResponse.baseResponse:type_name -> BaseResponse
	3,  // 9: H5ExtTransferResponse.jsApiResponse:type_name -> JsApiResponse
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_PcFinder_proto_init() }
func file_PcFinder_proto_init() {
	if File_PcFinder_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_PcFinder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*H5AuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PcFinder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*H5AuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PcFinder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferJsApiHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PcFinder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsApiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PcFinder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsApiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PcFinder_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*H5ExtTransferRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PcFinder_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*H5ExtTransferResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PcFinder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PcFinder_proto_goTypes,
		DependencyIndexes: file_PcFinder_proto_depIdxs,
		MessageInfos:      file_PcFinder_proto_msgTypes,
	}.Build()
	File_PcFinder_proto = out.File
	file_PcFinder_proto_rawDesc = nil
	file_PcFinder_proto_goTypes = nil
	file_PcFinder_proto_depIdxs = nil
}
