// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: RevokeMsg.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RevokeMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest    *BaseRequest `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	ClientMsgId    *string      `protobuf:"bytes,2,opt,name=clientMsgId" json:"clientMsgId,omitempty"`
	NewClientMsgId *uint32      `protobuf:"varint,3,req,name=newClientMsgId" json:"newClientMsgId,omitempty"`
	CreateTime     *uint32      `protobuf:"varint,4,req,name=createTime" json:"createTime,omitempty"`
	SvrMsgId       *uint32      `protobuf:"varint,5,req,name=svrMsgId" json:"svrMsgId,omitempty"`
	FromUserName   *string      `protobuf:"bytes,6,opt,name=fromUserName" json:"fromUserName,omitempty"`
	ToUserName     *string      `protobuf:"bytes,7,opt,name=toUserName" json:"toUserName,omitempty"`
	IndexOfRequest *uint32      `protobuf:"varint,8,req,name=indexOfRequest" json:"indexOfRequest,omitempty"`
	SvrNewMsgId    *uint64      `protobuf:"varint,9,opt,name=svrNewMsgId" json:"svrNewMsgId,omitempty"`
	RevokeTicket   *string      `protobuf:"bytes,10,opt,name=revokeTicket" json:"revokeTicket,omitempty"`
}

func (x *RevokeMsgRequest) Reset() {
	*x = RevokeMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RevokeMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMsgRequest) ProtoMessage() {}

func (x *RevokeMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_RevokeMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMsgRequest.ProtoReflect.Descriptor instead.
func (*RevokeMsgRequest) Descriptor() ([]byte, []int) {
	return file_RevokeMsg_proto_rawDescGZIP(), []int{0}
}

func (x *RevokeMsgRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *RevokeMsgRequest) GetClientMsgId() string {
	if x != nil && x.ClientMsgId != nil {
		return *x.ClientMsgId
	}
	return ""
}

func (x *RevokeMsgRequest) GetNewClientMsgId() uint32 {
	if x != nil && x.NewClientMsgId != nil {
		return *x.NewClientMsgId
	}
	return 0
}

func (x *RevokeMsgRequest) GetCreateTime() uint32 {
	if x != nil && x.CreateTime != nil {
		return *x.CreateTime
	}
	return 0
}

func (x *RevokeMsgRequest) GetSvrMsgId() uint32 {
	if x != nil && x.SvrMsgId != nil {
		return *x.SvrMsgId
	}
	return 0
}

func (x *RevokeMsgRequest) GetFromUserName() string {
	if x != nil && x.FromUserName != nil {
		return *x.FromUserName
	}
	return ""
}

func (x *RevokeMsgRequest) GetToUserName() string {
	if x != nil && x.ToUserName != nil {
		return *x.ToUserName
	}
	return ""
}

func (x *RevokeMsgRequest) GetIndexOfRequest() uint32 {
	if x != nil && x.IndexOfRequest != nil {
		return *x.IndexOfRequest
	}
	return 0
}

func (x *RevokeMsgRequest) GetSvrNewMsgId() uint64 {
	if x != nil && x.SvrNewMsgId != nil {
		return *x.SvrNewMsgId
	}
	return 0
}

func (x *RevokeMsgRequest) GetRevokeTicket() string {
	if x != nil && x.RevokeTicket != nil {
		return *x.RevokeTicket
	}
	return ""
}

type RevokeMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse *BaseResponse `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
	Introduction *string       `protobuf:"bytes,2,opt,name=introduction" json:"introduction,omitempty"`
	SysWording   *string       `protobuf:"bytes,3,opt,name=sysWording" json:"sysWording,omitempty"`
}

func (x *RevokeMsgResponse) Reset() {
	*x = RevokeMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RevokeMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMsgResponse) ProtoMessage() {}

func (x *RevokeMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_RevokeMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMsgResponse.ProtoReflect.Descriptor instead.
func (*RevokeMsgResponse) Descriptor() ([]byte, []int) {
	return file_RevokeMsg_proto_rawDescGZIP(), []int{1}
}

func (x *RevokeMsgResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *RevokeMsgResponse) GetIntroduction() string {
	if x != nil && x.Introduction != nil {
		return *x.Introduction
	}
	return ""
}

func (x *RevokeMsgResponse) GetSysWording() string {
	if x != nil && x.SysWording != nil {
		return *x.SysWording
	}
	return ""
}

var File_RevokeMsg_proto protoreflect.FileDescriptor

var file_RevokeMsg_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfa, 0x02, 0x0a, 0x10, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e,
	0x6e, 0x65, 0x77, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x0e, 0x6e, 0x65, 0x77, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x73, 0x67, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x76, 0x72, 0x4d, 0x73, 0x67, 0x49, 0x64,
	0x18, 0x05, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x76, 0x72, 0x4d, 0x73, 0x67, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x4f, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x08, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0e, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x4f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x73, 0x76, 0x72, 0x4e, 0x65, 0x77, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0b, 0x73, 0x76, 0x72, 0x4e, 0x65, 0x77, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x69,
	0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x79, 0x73, 0x57, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x57, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_RevokeMsg_proto_rawDescOnce sync.Once
	file_RevokeMsg_proto_rawDescData = file_RevokeMsg_proto_rawDesc
)

func file_RevokeMsg_proto_rawDescGZIP() []byte {
	file_RevokeMsg_proto_rawDescOnce.Do(func() {
		file_RevokeMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_RevokeMsg_proto_rawDescData)
	})
	return file_RevokeMsg_proto_rawDescData
}

var file_RevokeMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_RevokeMsg_proto_goTypes = []interface{}{
	(*RevokeMsgRequest)(nil),  // 0: RevokeMsgRequest
	(*RevokeMsgResponse)(nil), // 1: RevokeMsgResponse
	(*BaseRequest)(nil),       // 2: BaseRequest
	(*BaseResponse)(nil),      // 3: BaseResponse
}
var file_RevokeMsg_proto_depIdxs = []int32{
	2, // 0: RevokeMsgRequest.baseRequest:type_name -> BaseRequest
	3, // 1: RevokeMsgResponse.baseResponse:type_name -> BaseResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_RevokeMsg_proto_init() }
func file_RevokeMsg_proto_init() {
	if File_RevokeMsg_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_RevokeMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RevokeMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RevokeMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RevokeMsg_proto_goTypes,
		DependencyIndexes: file_RevokeMsg_proto_depIdxs,
		MessageInfos:      file_RevokeMsg_proto_msgTypes,
	}.Build()
	File_RevokeMsg_proto = out.File
	file_RevokeMsg_proto_rawDesc = nil
	file_RevokeMsg_proto_goTypes = nil
	file_RevokeMsg_proto_depIdxs = nil
}
