// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: SendPat.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendPatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest    *BaseRequest `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	FromUsername   *string      `protobuf:"bytes,2,opt,name=fromUsername" json:"fromUsername,omitempty"`
	ChatUsername   *string      `protobuf:"bytes,3,opt,name=chatUsername" json:"chatUsername,omitempty"`
	PattedUsername *string      `protobuf:"bytes,4,opt,name=pattedUsername" json:"pattedUsername,omitempty"`
	ClientMsgId    *string      `protobuf:"bytes,5,opt,name=clientMsgId" json:"clientMsgId,omitempty"`
	Scene          *uint32      `protobuf:"varint,6,opt,name=scene" json:"scene,omitempty"`
}

func (x *SendPatRequest) Reset() {
	*x = SendPatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SendPat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPatRequest) ProtoMessage() {}

func (x *SendPatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SendPat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPatRequest.ProtoReflect.Descriptor instead.
func (*SendPatRequest) Descriptor() ([]byte, []int) {
	return file_SendPat_proto_rawDescGZIP(), []int{0}
}

func (x *SendPatRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *SendPatRequest) GetFromUsername() string {
	if x != nil && x.FromUsername != nil {
		return *x.FromUsername
	}
	return ""
}

func (x *SendPatRequest) GetChatUsername() string {
	if x != nil && x.ChatUsername != nil {
		return *x.ChatUsername
	}
	return ""
}

func (x *SendPatRequest) GetPattedUsername() string {
	if x != nil && x.PattedUsername != nil {
		return *x.PattedUsername
	}
	return ""
}

func (x *SendPatRequest) GetClientMsgId() string {
	if x != nil && x.ClientMsgId != nil {
		return *x.ClientMsgId
	}
	return ""
}

func (x *SendPatRequest) GetScene() uint32 {
	if x != nil && x.Scene != nil {
		return *x.Scene
	}
	return 0
}

type SendPatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse     *BaseResponse `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	Tmpl             *string       `protobuf:"bytes,2,opt,name=tmpl" json:"tmpl,omitempty"`
	SelfMsg          *string       `protobuf:"bytes,3,opt,name=selfMsg" json:"selfMsg,omitempty"`
	PatSuffix        *string       `protobuf:"bytes,4,opt,name=patSuffix" json:"patSuffix,omitempty"`
	MsgId            *uint64       `protobuf:"varint,5,opt,name=msgId" json:"msgId,omitempty"`
	PatSuffixVersion *uint32       `protobuf:"varint,6,opt,name=patSuffixVersion" json:"patSuffixVersion,omitempty"`
}

func (x *SendPatResponse) Reset() {
	*x = SendPatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SendPat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPatResponse) ProtoMessage() {}

func (x *SendPatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SendPat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPatResponse.ProtoReflect.Descriptor instead.
func (*SendPatResponse) Descriptor() ([]byte, []int) {
	return file_SendPat_proto_rawDescGZIP(), []int{1}
}

func (x *SendPatResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *SendPatResponse) GetTmpl() string {
	if x != nil && x.Tmpl != nil {
		return *x.Tmpl
	}
	return ""
}

func (x *SendPatResponse) GetSelfMsg() string {
	if x != nil && x.SelfMsg != nil {
		return *x.SelfMsg
	}
	return ""
}

func (x *SendPatResponse) GetPatSuffix() string {
	if x != nil && x.PatSuffix != nil {
		return *x.PatSuffix
	}
	return ""
}

func (x *SendPatResponse) GetMsgId() uint64 {
	if x != nil && x.MsgId != nil {
		return *x.MsgId
	}
	return 0
}

func (x *SendPatResponse) GetPatSuffixVersion() uint32 {
	if x != nil && x.PatSuffixVersion != nil {
		return *x.PatSuffixVersion
	}
	return 0
}

var File_SendPat_proto protoreflect.FileDescriptor

var file_SendPat_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xe8, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72,
	0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x68,
	0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x70, 0x61, 0x74, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x61, 0x74, 0x74, 0x65, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x22, 0xd2,
	0x01, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6d, 0x70, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6d, 0x70, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x6c,
	0x66, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x6c, 0x66,
	0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x74, 0x53, 0x75, 0x66, 0x66, 0x69, 0x78,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x74, 0x53, 0x75, 0x66, 0x66, 0x69,
	0x78, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x70, 0x61, 0x74, 0x53, 0x75,
	0x66, 0x66, 0x69, 0x78, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x10, 0x70, 0x61, 0x74, 0x53, 0x75, 0x66, 0x66, 0x69, 0x78, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73,
	0x67,
}

var (
	file_SendPat_proto_rawDescOnce sync.Once
	file_SendPat_proto_rawDescData = file_SendPat_proto_rawDesc
)

func file_SendPat_proto_rawDescGZIP() []byte {
	file_SendPat_proto_rawDescOnce.Do(func() {
		file_SendPat_proto_rawDescData = protoimpl.X.CompressGZIP(file_SendPat_proto_rawDescData)
	})
	return file_SendPat_proto_rawDescData
}

var file_SendPat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_SendPat_proto_goTypes = []interface{}{
	(*SendPatRequest)(nil),  // 0: SendPatRequest
	(*SendPatResponse)(nil), // 1: SendPatResponse
	(*BaseRequest)(nil),     // 2: BaseRequest
	(*BaseResponse)(nil),    // 3: BaseResponse
}
var file_SendPat_proto_depIdxs = []int32{
	2, // 0: SendPatRequest.baseRequest:type_name -> BaseRequest
	3, // 1: SendPatResponse.baseResponse:type_name -> BaseResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SendPat_proto_init() }
func file_SendPat_proto_init() {
	if File_SendPat_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SendPat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SendPat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SendPat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SendPat_proto_goTypes,
		DependencyIndexes: file_SendPat_proto_depIdxs,
		MessageInfos:      file_SendPat_proto_msgTypes,
	}.Build()
	File_SendPat_proto = out.File
	file_SendPat_proto_rawDesc = nil
	file_SendPat_proto_goTypes = nil
	file_SendPat_proto_depIdxs = nil
}
