// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: SnsAdObjectDetail.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnsAdObjectDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest *BaseRequest      `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	Id          *uint64           `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Scene       *uint32           `protobuf:"varint,3,opt,name=scene" json:"scene,omitempty"`
	Session     *SKBuiltinBufferT `protobuf:"bytes,4,opt,name=session" json:"session,omitempty"`
}

func (x *SnsAdObjectDetailRequest) Reset() {
	*x = SnsAdObjectDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SnsAdObjectDetail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnsAdObjectDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnsAdObjectDetailRequest) ProtoMessage() {}

func (x *SnsAdObjectDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SnsAdObjectDetail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnsAdObjectDetailRequest.ProtoReflect.Descriptor instead.
func (*SnsAdObjectDetailRequest) Descriptor() ([]byte, []int) {
	return file_SnsAdObjectDetail_proto_rawDescGZIP(), []int{0}
}

func (x *SnsAdObjectDetailRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *SnsAdObjectDetailRequest) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SnsAdObjectDetailRequest) GetScene() uint32 {
	if x != nil && x.Scene != nil {
		return *x.Scene
	}
	return 0
}

func (x *SnsAdObjectDetailRequest) GetSession() *SKBuiltinBufferT {
	if x != nil {
		return x.Session
	}
	return nil
}

type SnsAdObjectDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse *BaseResponse     `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
	Object       *SnsAdObject      `protobuf:"bytes,2,req,name=object" json:"object,omitempty"`
	Session      *SKBuiltinBufferT `protobuf:"bytes,3,opt,name=session" json:"session,omitempty"`
}

func (x *SnsAdObjectDetailResponse) Reset() {
	*x = SnsAdObjectDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SnsAdObjectDetail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnsAdObjectDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnsAdObjectDetailResponse) ProtoMessage() {}

func (x *SnsAdObjectDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SnsAdObjectDetail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnsAdObjectDetailResponse.ProtoReflect.Descriptor instead.
func (*SnsAdObjectDetailResponse) Descriptor() ([]byte, []int) {
	return file_SnsAdObjectDetail_proto_rawDescGZIP(), []int{1}
}

func (x *SnsAdObjectDetailResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *SnsAdObjectDetailResponse) GetObject() *SnsAdObject {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *SnsAdObjectDetailResponse) GetSession() *SKBuiltinBufferT {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_SnsAdObjectDetail_proto protoreflect.FileDescriptor

var file_SnsAdObjectDetail_proto_rawDesc = []byte{
	0x0a, 0x17, 0x53, 0x6e, 0x73, 0x41, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f,
	0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d,
	0x69, 0x63, 0x72, 0x6f, 0x53, 0x6e, 0x73, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x9e, 0x01, 0x0a, 0x18, 0x53, 0x6e, 0x73, 0x41, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69,
	0x6e, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0xa2, 0x01, 0x0a, 0x19, 0x53, 0x6e, 0x73, 0x41, 0x64, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x6e, 0x73, 0x41, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42,
	0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x52, 0x07,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_SnsAdObjectDetail_proto_rawDescOnce sync.Once
	file_SnsAdObjectDetail_proto_rawDescData = file_SnsAdObjectDetail_proto_rawDesc
)

func file_SnsAdObjectDetail_proto_rawDescGZIP() []byte {
	file_SnsAdObjectDetail_proto_rawDescOnce.Do(func() {
		file_SnsAdObjectDetail_proto_rawDescData = protoimpl.X.CompressGZIP(file_SnsAdObjectDetail_proto_rawDescData)
	})
	return file_SnsAdObjectDetail_proto_rawDescData
}

var file_SnsAdObjectDetail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_SnsAdObjectDetail_proto_goTypes = []interface{}{
	(*SnsAdObjectDetailRequest)(nil),  // 0: SnsAdObjectDetailRequest
	(*SnsAdObjectDetailResponse)(nil), // 1: SnsAdObjectDetailResponse
	(*BaseRequest)(nil),               // 2: BaseRequest
	(*SKBuiltinBufferT)(nil),          // 3: SKBuiltinBuffer_t
	(*BaseResponse)(nil),              // 4: BaseResponse
	(*SnsAdObject)(nil),               // 5: SnsAdObject
}
var file_SnsAdObjectDetail_proto_depIdxs = []int32{
	2, // 0: SnsAdObjectDetailRequest.baseRequest:type_name -> BaseRequest
	3, // 1: SnsAdObjectDetailRequest.session:type_name -> SKBuiltinBuffer_t
	4, // 2: SnsAdObjectDetailResponse.baseResponse:type_name -> BaseResponse
	5, // 3: SnsAdObjectDetailResponse.object:type_name -> SnsAdObject
	3, // 4: SnsAdObjectDetailResponse.session:type_name -> SKBuiltinBuffer_t
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_SnsAdObjectDetail_proto_init() }
func file_SnsAdObjectDetail_proto_init() {
	if File_SnsAdObjectDetail_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	file_MicroSnsBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SnsAdObjectDetail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnsAdObjectDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SnsAdObjectDetail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnsAdObjectDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SnsAdObjectDetail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SnsAdObjectDetail_proto_goTypes,
		DependencyIndexes: file_SnsAdObjectDetail_proto_depIdxs,
		MessageInfos:      file_SnsAdObjectDetail_proto_msgTypes,
	}.Build()
	File_SnsAdObjectDetail_proto = out.File
	file_SnsAdObjectDetail_proto_rawDesc = nil
	file_SnsAdObjectDetail_proto_goTypes = nil
	file_SnsAdObjectDetail_proto_depIdxs = nil
}
