// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: SnsObjectDetail.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnsObjectDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest *BaseRequest `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	Id          *uint64      `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	GroupDetail *uint32      `protobuf:"varint,3,opt,name=groupDetail" json:"groupDetail,omitempty"`
}

func (x *SnsObjectDetailRequest) Reset() {
	*x = SnsObjectDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SnsObjectDetail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnsObjectDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnsObjectDetailRequest) ProtoMessage() {}

func (x *SnsObjectDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SnsObjectDetail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnsObjectDetailRequest.ProtoReflect.Descriptor instead.
func (*SnsObjectDetailRequest) Descriptor() ([]byte, []int) {
	return file_SnsObjectDetail_proto_rawDescGZIP(), []int{0}
}

func (x *SnsObjectDetailRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *SnsObjectDetailRequest) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SnsObjectDetailRequest) GetGroupDetail() uint32 {
	if x != nil && x.GroupDetail != nil {
		return *x.GroupDetail
	}
	return 0
}

type SnsObjectDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse *BaseResponse `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
	Object       *SnsObject    `protobuf:"bytes,2,req,name=object" json:"object,omitempty"`
}

func (x *SnsObjectDetailResponse) Reset() {
	*x = SnsObjectDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SnsObjectDetail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnsObjectDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnsObjectDetailResponse) ProtoMessage() {}

func (x *SnsObjectDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SnsObjectDetail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnsObjectDetailResponse.ProtoReflect.Descriptor instead.
func (*SnsObjectDetailResponse) Descriptor() ([]byte, []int) {
	return file_SnsObjectDetail_proto_rawDescGZIP(), []int{1}
}

func (x *SnsObjectDetailResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *SnsObjectDetailResponse) GetObject() *SnsObject {
	if x != nil {
		return x.Object
	}
	return nil
}

var File_SnsObjectDetail_proto protoreflect.FileDescriptor

var file_SnsObjectDetail_proto_rawDesc = []byte{
	0x0a, 0x15, 0x53, 0x6e, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73,
	0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x69, 0x63,
	0x72, 0x6f, 0x53, 0x6e, 0x73, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x7a, 0x0a, 0x16, 0x53, 0x6e, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x70, 0x0a, 0x17, 0x53,
	0x6e, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x6e, 0x73, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_SnsObjectDetail_proto_rawDescOnce sync.Once
	file_SnsObjectDetail_proto_rawDescData = file_SnsObjectDetail_proto_rawDesc
)

func file_SnsObjectDetail_proto_rawDescGZIP() []byte {
	file_SnsObjectDetail_proto_rawDescOnce.Do(func() {
		file_SnsObjectDetail_proto_rawDescData = protoimpl.X.CompressGZIP(file_SnsObjectDetail_proto_rawDescData)
	})
	return file_SnsObjectDetail_proto_rawDescData
}

var file_SnsObjectDetail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_SnsObjectDetail_proto_goTypes = []interface{}{
	(*SnsObjectDetailRequest)(nil),  // 0: SnsObjectDetailRequest
	(*SnsObjectDetailResponse)(nil), // 1: SnsObjectDetailResponse
	(*BaseRequest)(nil),             // 2: BaseRequest
	(*BaseResponse)(nil),            // 3: BaseResponse
	(*SnsObject)(nil),               // 4: SnsObject
}
var file_SnsObjectDetail_proto_depIdxs = []int32{
	2, // 0: SnsObjectDetailRequest.baseRequest:type_name -> BaseRequest
	3, // 1: SnsObjectDetailResponse.baseResponse:type_name -> BaseResponse
	4, // 2: SnsObjectDetailResponse.object:type_name -> SnsObject
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_SnsObjectDetail_proto_init() }
func file_SnsObjectDetail_proto_init() {
	if File_SnsObjectDetail_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	file_MicroSnsBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SnsObjectDetail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnsObjectDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SnsObjectDetail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnsObjectDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SnsObjectDetail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SnsObjectDetail_proto_goTypes,
		DependencyIndexes: file_SnsObjectDetail_proto_depIdxs,
		MessageInfos:      file_SnsObjectDetail_proto_msgTypes,
	}.Build()
	File_SnsObjectDetail_proto = out.File
	file_SnsObjectDetail_proto_rawDesc = nil
	file_SnsObjectDetail_proto_goTypes = nil
	file_SnsObjectDetail_proto_depIdxs = nil
}
