// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: SnsObjectOp.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnsYearMonthInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year   *uint32 `protobuf:"varint,1,req,name=year" json:"year,omitempty"`
	Month  *uint32 `protobuf:"varint,2,req,name=month" json:"month,omitempty"`
	LastId *uint64 `protobuf:"varint,3,req,name=lastId" json:"lastId,omitempty"`
}

func (x *SnsYearMonthInfo) Reset() {
	*x = SnsYearMonthInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SnsObjectOp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnsYearMonthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnsYearMonthInfo) ProtoMessage() {}

func (x *SnsYearMonthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SnsObjectOp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnsYearMonthInfo.ProtoReflect.Descriptor instead.
func (*SnsYearMonthInfo) Descriptor() ([]byte, []int) {
	return file_SnsObjectOp_proto_rawDescGZIP(), []int{0}
}

func (x *SnsYearMonthInfo) GetYear() uint32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *SnsYearMonthInfo) GetMonth() uint32 {
	if x != nil && x.Month != nil {
		return *x.Month
	}
	return 0
}

func (x *SnsYearMonthInfo) GetLastId() uint64 {
	if x != nil && x.LastId != nil {
		return *x.LastId
	}
	return 0
}

type SnsObjectOpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest *BaseRequest      `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	OpCount     *uint32           `protobuf:"varint,2,req,name=opCount" json:"opCount,omitempty"`
	OpList      []*SnsObjectOp    `protobuf:"bytes,3,rep,name=opList" json:"opList,omitempty"`
	ExtSpamInfo *SKBuiltinBufferT `protobuf:"bytes,4,opt,name=extSpamInfo" json:"extSpamInfo,omitempty"`
}

func (x *SnsObjectOpRequest) Reset() {
	*x = SnsObjectOpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SnsObjectOp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnsObjectOpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnsObjectOpRequest) ProtoMessage() {}

func (x *SnsObjectOpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SnsObjectOp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnsObjectOpRequest.ProtoReflect.Descriptor instead.
func (*SnsObjectOpRequest) Descriptor() ([]byte, []int) {
	return file_SnsObjectOp_proto_rawDescGZIP(), []int{1}
}

func (x *SnsObjectOpRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *SnsObjectOpRequest) GetOpCount() uint32 {
	if x != nil && x.OpCount != nil {
		return *x.OpCount
	}
	return 0
}

func (x *SnsObjectOpRequest) GetOpList() []*SnsObjectOp {
	if x != nil {
		return x.OpList
	}
	return nil
}

func (x *SnsObjectOpRequest) GetExtSpamInfo() *SKBuiltinBufferT {
	if x != nil {
		return x.ExtSpamInfo
	}
	return nil
}

type SnsObjectOpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse        *BaseResponse       `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
	OpCount             *uint32             `protobuf:"varint,2,req,name=opCount" json:"opCount,omitempty"`
	OpRetList           []int32             `protobuf:"varint,3,rep,packed,name=opRetList" json:"opRetList,omitempty"`
	UpdateYearMonthInfo *uint32             `protobuf:"varint,4,opt,name=updateYearMonthInfo" json:"updateYearMonthInfo,omitempty"`
	YearMonthInfoCount  *uint32             `protobuf:"varint,5,opt,name=yearMonthInfoCount" json:"yearMonthInfoCount,omitempty"`
	YearMonthInfoList   []*SnsYearMonthInfo `protobuf:"bytes,6,rep,name=yearMonthInfoList" json:"yearMonthInfoList,omitempty"`
}

func (x *SnsObjectOpResponse) Reset() {
	*x = SnsObjectOpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SnsObjectOp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnsObjectOpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnsObjectOpResponse) ProtoMessage() {}

func (x *SnsObjectOpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SnsObjectOp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnsObjectOpResponse.ProtoReflect.Descriptor instead.
func (*SnsObjectOpResponse) Descriptor() ([]byte, []int) {
	return file_SnsObjectOp_proto_rawDescGZIP(), []int{2}
}

func (x *SnsObjectOpResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *SnsObjectOpResponse) GetOpCount() uint32 {
	if x != nil && x.OpCount != nil {
		return *x.OpCount
	}
	return 0
}

func (x *SnsObjectOpResponse) GetOpRetList() []int32 {
	if x != nil {
		return x.OpRetList
	}
	return nil
}

func (x *SnsObjectOpResponse) GetUpdateYearMonthInfo() uint32 {
	if x != nil && x.UpdateYearMonthInfo != nil {
		return *x.UpdateYearMonthInfo
	}
	return 0
}

func (x *SnsObjectOpResponse) GetYearMonthInfoCount() uint32 {
	if x != nil && x.YearMonthInfoCount != nil {
		return *x.YearMonthInfoCount
	}
	return 0
}

func (x *SnsObjectOpResponse) GetYearMonthInfoList() []*SnsYearMonthInfo {
	if x != nil {
		return x.YearMonthInfoList
	}
	return nil
}

var File_SnsObjectOp_proto protoreflect.FileDescriptor

var file_SnsObjectOp_proto_rawDesc = []byte{
	0x0a, 0x11, 0x53, 0x6e, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4f, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x53, 0x6e,
	0x73, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x10, 0x53,
	0x6e, 0x73, 0x59, 0x65, 0x61, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x04, 0x79,
	0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x0d, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x04, 0x52, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x49,
	0x64, 0x22, 0xba, 0x01, 0x0a, 0x12, 0x53, 0x6e, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4f,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x07, 0x6f, 0x70, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x6e, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4f, 0x70,
	0x52, 0x06, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x53,
	0x70, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x5f,
	0x74, 0x52, 0x0b, 0x65, 0x78, 0x74, 0x53, 0x70, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xa7,
	0x02, 0x0a, 0x13, 0x53, 0x6e, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4f, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x07, 0x6f, 0x70, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x09, 0x6f, 0x70, 0x52, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x42, 0x02, 0x10, 0x01, 0x52, 0x09, 0x6f, 0x70, 0x52, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x59,
	0x65, 0x61, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x13, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x59, 0x65, 0x61, 0x72, 0x4d, 0x6f,
	0x6e, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e, 0x0a, 0x12, 0x79, 0x65, 0x61, 0x72, 0x4d,
	0x6f, 0x6e, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x12, 0x79, 0x65, 0x61, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x49, 0x6e,
	0x66, 0x6f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x11, 0x79, 0x65, 0x61, 0x72, 0x4d,
	0x6f, 0x6e, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x53, 0x6e, 0x73, 0x59, 0x65, 0x61, 0x72, 0x4d, 0x6f, 0x6e, 0x74,
	0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x11, 0x79, 0x65, 0x61, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x68,
	0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_SnsObjectOp_proto_rawDescOnce sync.Once
	file_SnsObjectOp_proto_rawDescData = file_SnsObjectOp_proto_rawDesc
)

func file_SnsObjectOp_proto_rawDescGZIP() []byte {
	file_SnsObjectOp_proto_rawDescOnce.Do(func() {
		file_SnsObjectOp_proto_rawDescData = protoimpl.X.CompressGZIP(file_SnsObjectOp_proto_rawDescData)
	})
	return file_SnsObjectOp_proto_rawDescData
}

var file_SnsObjectOp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_SnsObjectOp_proto_goTypes = []interface{}{
	(*SnsYearMonthInfo)(nil),    // 0: SnsYearMonthInfo
	(*SnsObjectOpRequest)(nil),  // 1: SnsObjectOpRequest
	(*SnsObjectOpResponse)(nil), // 2: SnsObjectOpResponse
	(*BaseRequest)(nil),         // 3: BaseRequest
	(*SnsObjectOp)(nil),         // 4: SnsObjectOp
	(*SKBuiltinBufferT)(nil),    // 5: SKBuiltinBuffer_t
	(*BaseResponse)(nil),        // 6: BaseResponse
}
var file_SnsObjectOp_proto_depIdxs = []int32{
	3, // 0: SnsObjectOpRequest.baseRequest:type_name -> BaseRequest
	4, // 1: SnsObjectOpRequest.opList:type_name -> SnsObjectOp
	5, // 2: SnsObjectOpRequest.extSpamInfo:type_name -> SKBuiltinBuffer_t
	6, // 3: SnsObjectOpResponse.baseResponse:type_name -> BaseResponse
	0, // 4: SnsObjectOpResponse.yearMonthInfoList:type_name -> SnsYearMonthInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_SnsObjectOp_proto_init() }
func file_SnsObjectOp_proto_init() {
	if File_SnsObjectOp_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	file_MicroSnsBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SnsObjectOp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnsYearMonthInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SnsObjectOp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnsObjectOpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SnsObjectOp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnsObjectOpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SnsObjectOp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SnsObjectOp_proto_goTypes,
		DependencyIndexes: file_SnsObjectOp_proto_depIdxs,
		MessageInfos:      file_SnsObjectOp_proto_msgTypes,
	}.Build()
	File_SnsObjectOp_proto = out.File
	file_SnsObjectOp_proto_rawDesc = nil
	file_SnsObjectOp_proto_goTypes = nil
	file_SnsObjectOp_proto_depIdxs = nil
}
