// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: SnsSync.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnsSyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest *BaseRequest      `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	Selector    *uint32           `protobuf:"varint,2,req,name=selector" json:"selector,omitempty"`
	KeyBuf      *SKBuiltinBufferT `protobuf:"bytes,3,req,name=keyBuf" json:"keyBuf,omitempty"`
}

func (x *SnsSyncRequest) Reset() {
	*x = SnsSyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SnsSync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnsSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnsSyncRequest) ProtoMessage() {}

func (x *SnsSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SnsSync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnsSyncRequest.ProtoReflect.Descriptor instead.
func (*SnsSyncRequest) Descriptor() ([]byte, []int) {
	return file_SnsSync_proto_rawDescGZIP(), []int{0}
}

func (x *SnsSyncRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *SnsSyncRequest) GetSelector() uint32 {
	if x != nil && x.Selector != nil {
		return *x.Selector
	}
	return 0
}

func (x *SnsSyncRequest) GetKeyBuf() *SKBuiltinBufferT {
	if x != nil {
		return x.KeyBuf
	}
	return nil
}

type SnsSyncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse *BaseResponse     `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
	CmdList      *CmdList          `protobuf:"bytes,2,req,name=cmdList" json:"cmdList,omitempty"`
	ContinueFlag *uint32           `protobuf:"varint,3,req,name=continueFlag" json:"continueFlag,omitempty"`
	KeyBuf       *SKBuiltinBufferT `protobuf:"bytes,4,req,name=keyBuf" json:"keyBuf,omitempty"`
}

func (x *SnsSyncResponse) Reset() {
	*x = SnsSyncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SnsSync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnsSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnsSyncResponse) ProtoMessage() {}

func (x *SnsSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SnsSync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnsSyncResponse.ProtoReflect.Descriptor instead.
func (*SnsSyncResponse) Descriptor() ([]byte, []int) {
	return file_SnsSync_proto_rawDescGZIP(), []int{1}
}

func (x *SnsSyncResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *SnsSyncResponse) GetCmdList() *CmdList {
	if x != nil {
		return x.CmdList
	}
	return nil
}

func (x *SnsSyncResponse) GetContinueFlag() uint32 {
	if x != nil && x.ContinueFlag != nil {
		return *x.ContinueFlag
	}
	return 0
}

func (x *SnsSyncResponse) GetKeyBuf() *SKBuiltinBufferT {
	if x != nil {
		return x.KeyBuf
	}
	return nil
}

var File_SnsSync_proto protoreflect.FileDescriptor

var file_SnsSync_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x53, 0x6e, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x88, 0x01, 0x0a, 0x0e, 0x53, 0x6e, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x42, 0x75, 0x66, 0x18, 0x03, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x42, 0x75,
	0x66, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x42, 0x75, 0x66, 0x22, 0xb8,
	0x01, 0x0a, 0x0f, 0x53, 0x6e, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x63, 0x6d, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x6d, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x07, 0x63, 0x6d, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x74, 0x69, 0x6e, 0x75, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52,
	0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x2a, 0x0a,
	0x06, 0x6b, 0x65, 0x79, 0x42, 0x75, 0x66, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x5f,
	0x74, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x42, 0x75, 0x66, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_SnsSync_proto_rawDescOnce sync.Once
	file_SnsSync_proto_rawDescData = file_SnsSync_proto_rawDesc
)

func file_SnsSync_proto_rawDescGZIP() []byte {
	file_SnsSync_proto_rawDescOnce.Do(func() {
		file_SnsSync_proto_rawDescData = protoimpl.X.CompressGZIP(file_SnsSync_proto_rawDescData)
	})
	return file_SnsSync_proto_rawDescData
}

var file_SnsSync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_SnsSync_proto_goTypes = []interface{}{
	(*SnsSyncRequest)(nil),   // 0: SnsSyncRequest
	(*SnsSyncResponse)(nil),  // 1: SnsSyncResponse
	(*BaseRequest)(nil),      // 2: BaseRequest
	(*SKBuiltinBufferT)(nil), // 3: SKBuiltinBuffer_t
	(*BaseResponse)(nil),     // 4: BaseResponse
	(*CmdList)(nil),          // 5: CmdList
}
var file_SnsSync_proto_depIdxs = []int32{
	2, // 0: SnsSyncRequest.baseRequest:type_name -> BaseRequest
	3, // 1: SnsSyncRequest.keyBuf:type_name -> SKBuiltinBuffer_t
	4, // 2: SnsSyncResponse.baseResponse:type_name -> BaseResponse
	5, // 3: SnsSyncResponse.cmdList:type_name -> CmdList
	3, // 4: SnsSyncResponse.keyBuf:type_name -> SKBuiltinBuffer_t
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_SnsSync_proto_init() }
func file_SnsSync_proto_init() {
	if File_SnsSync_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SnsSync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnsSyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SnsSync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnsSyncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SnsSync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SnsSync_proto_goTypes,
		DependencyIndexes: file_SnsSync_proto_depIdxs,
		MessageInfos:      file_SnsSync_proto_msgTypes,
	}.Build()
	File_SnsSync_proto = out.File
	file_SnsSync_proto_rawDesc = nil
	file_SnsSync_proto_goTypes = nil
	file_SnsSync_proto_depIdxs = nil
}
