// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: StatusNotify.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusNotifyUnreadChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName     *string `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	LastReadTime *uint32 `protobuf:"varint,2,req,name=lastReadTime" json:"lastReadTime,omitempty"`
}

func (x *StatusNotifyUnreadChat) Reset() {
	*x = StatusNotifyUnreadChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StatusNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusNotifyUnreadChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusNotifyUnreadChat) ProtoMessage() {}

func (x *StatusNotifyUnreadChat) ProtoReflect() protoreflect.Message {
	mi := &file_StatusNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusNotifyUnreadChat.ProtoReflect.Descriptor instead.
func (*StatusNotifyUnreadChat) Descriptor() ([]byte, []int) {
	return file_StatusNotify_proto_rawDescGZIP(), []int{0}
}

func (x *StatusNotifyUnreadChat) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *StatusNotifyUnreadChat) GetLastReadTime() uint32 {
	if x != nil && x.LastReadTime != nil {
		return *x.LastReadTime
	}
	return 0
}

type StatusNotifyFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Arg  *string `protobuf:"bytes,2,opt,name=arg" json:"arg,omitempty"`
}

func (x *StatusNotifyFunction) Reset() {
	*x = StatusNotifyFunction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StatusNotify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusNotifyFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusNotifyFunction) ProtoMessage() {}

func (x *StatusNotifyFunction) ProtoReflect() protoreflect.Message {
	mi := &file_StatusNotify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusNotifyFunction.ProtoReflect.Descriptor instead.
func (*StatusNotifyFunction) Descriptor() ([]byte, []int) {
	return file_StatusNotify_proto_rawDescGZIP(), []int{1}
}

func (x *StatusNotifyFunction) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *StatusNotifyFunction) GetArg() string {
	if x != nil && x.Arg != nil {
		return *x.Arg
	}
	return ""
}

type StatusNotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest         *BaseRequest              `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	Code                *uint32                   `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	FromUserName        *string                   `protobuf:"bytes,3,opt,name=fromUserName" json:"fromUserName,omitempty"`
	ToUserName          *string                   `protobuf:"bytes,4,opt,name=toUserName" json:"toUserName,omitempty"`
	ClientMsgId         *string                   `protobuf:"bytes,5,opt,name=clientMsgId" json:"clientMsgId,omitempty"`
	UnreadChatListCount *uint32                   `protobuf:"varint,6,opt,name=unreadChatListCount" json:"unreadChatListCount,omitempty"`
	UnreadChatList      []*StatusNotifyUnreadChat `protobuf:"bytes,7,rep,name=unreadChatList" json:"unreadChatList,omitempty"`
	Function            *StatusNotifyFunction     `protobuf:"bytes,8,opt,name=function" json:"function,omitempty"`
	UnreadFunctionCount *uint32                   `protobuf:"varint,9,opt,name=unreadFunctionCount" json:"unreadFunctionCount,omitempty"`
	UnreadFunctionList  []*StatusNotifyFunction   `protobuf:"bytes,10,rep,name=unreadFunctionList" json:"unreadFunctionList,omitempty"`
}

func (x *StatusNotifyRequest) Reset() {
	*x = StatusNotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StatusNotify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusNotifyRequest) ProtoMessage() {}

func (x *StatusNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_StatusNotify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusNotifyRequest.ProtoReflect.Descriptor instead.
func (*StatusNotifyRequest) Descriptor() ([]byte, []int) {
	return file_StatusNotify_proto_rawDescGZIP(), []int{2}
}

func (x *StatusNotifyRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *StatusNotifyRequest) GetCode() uint32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *StatusNotifyRequest) GetFromUserName() string {
	if x != nil && x.FromUserName != nil {
		return *x.FromUserName
	}
	return ""
}

func (x *StatusNotifyRequest) GetToUserName() string {
	if x != nil && x.ToUserName != nil {
		return *x.ToUserName
	}
	return ""
}

func (x *StatusNotifyRequest) GetClientMsgId() string {
	if x != nil && x.ClientMsgId != nil {
		return *x.ClientMsgId
	}
	return ""
}

func (x *StatusNotifyRequest) GetUnreadChatListCount() uint32 {
	if x != nil && x.UnreadChatListCount != nil {
		return *x.UnreadChatListCount
	}
	return 0
}

func (x *StatusNotifyRequest) GetUnreadChatList() []*StatusNotifyUnreadChat {
	if x != nil {
		return x.UnreadChatList
	}
	return nil
}

func (x *StatusNotifyRequest) GetFunction() *StatusNotifyFunction {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *StatusNotifyRequest) GetUnreadFunctionCount() uint32 {
	if x != nil && x.UnreadFunctionCount != nil {
		return *x.UnreadFunctionCount
	}
	return 0
}

func (x *StatusNotifyRequest) GetUnreadFunctionList() []*StatusNotifyFunction {
	if x != nil {
		return x.UnreadFunctionList
	}
	return nil
}

type ChatContact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName *string `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
}

func (x *ChatContact) Reset() {
	*x = ChatContact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StatusNotify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatContact) ProtoMessage() {}

func (x *ChatContact) ProtoReflect() protoreflect.Message {
	mi := &file_StatusNotify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatContact.ProtoReflect.Descriptor instead.
func (*ChatContact) Descriptor() ([]byte, []int) {
	return file_StatusNotify_proto_rawDescGZIP(), []int{3}
}

func (x *ChatContact) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

type StatusNotifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse     *BaseResponse  `protobuf:"bytes,1,req,name=BaseResponse" json:"BaseResponse,omitempty"`
	MsgId            *uint32        `protobuf:"varint,2,req,name=MsgId" json:"MsgId,omitempty"`
	NewMsgId         *uint64        `protobuf:"varint,3,opt,name=NewMsgId" json:"NewMsgId,omitempty"`
	ChatContactCount *uint32        `protobuf:"varint,4,opt,name=ChatContactCount" json:"ChatContactCount,omitempty"`
	ChatContactList  []*ChatContact `protobuf:"bytes,5,rep,name=ChatContactList" json:"ChatContactList,omitempty"`
}

func (x *StatusNotifyResponse) Reset() {
	*x = StatusNotifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StatusNotify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusNotifyResponse) ProtoMessage() {}

func (x *StatusNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_StatusNotify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusNotifyResponse.ProtoReflect.Descriptor instead.
func (*StatusNotifyResponse) Descriptor() ([]byte, []int) {
	return file_StatusNotify_proto_rawDescGZIP(), []int{4}
}

func (x *StatusNotifyResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *StatusNotifyResponse) GetMsgId() uint32 {
	if x != nil && x.MsgId != nil {
		return *x.MsgId
	}
	return 0
}

func (x *StatusNotifyResponse) GetNewMsgId() uint64 {
	if x != nil && x.NewMsgId != nil {
		return *x.NewMsgId
	}
	return 0
}

func (x *StatusNotifyResponse) GetChatContactCount() uint32 {
	if x != nil && x.ChatContactCount != nil {
		return *x.ChatContactCount
	}
	return 0
}

func (x *StatusNotifyResponse) GetChatContactList() []*ChatContact {
	if x != nil {
		return x.ChatContactList
	}
	return nil
}

var File_StatusNotify_proto protoreflect.FileDescriptor

var file_StatusNotify_proto_rawDesc = []byte{
	0x0a, 0x12, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x68,
	0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x72, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x72, 0x67,
	0x22, 0xde, 0x03, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x30, 0x0a, 0x13, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x13, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x0e, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x68,
	0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x6e, 0x72, 0x65, 0x61,
	0x64, 0x43, 0x68, 0x61, 0x74, 0x52, 0x0e, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x13, 0x75, 0x6e, 0x72, 0x65,
	0x61, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x45, 0x0a, 0x12, 0x75, 0x6e,
	0x72, 0x65, 0x61, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x12, 0x75,
	0x6e, 0x72, 0x65, 0x61, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x29, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xdf, 0x01, 0x0a,
	0x14, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x4e, 0x65, 0x77, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x4e, 0x65, 0x77, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x43, 0x68,
	0x61, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x0f, 0x43,
	0x68, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_StatusNotify_proto_rawDescOnce sync.Once
	file_StatusNotify_proto_rawDescData = file_StatusNotify_proto_rawDesc
)

func file_StatusNotify_proto_rawDescGZIP() []byte {
	file_StatusNotify_proto_rawDescOnce.Do(func() {
		file_StatusNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_StatusNotify_proto_rawDescData)
	})
	return file_StatusNotify_proto_rawDescData
}

var file_StatusNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_StatusNotify_proto_goTypes = []interface{}{
	(*StatusNotifyUnreadChat)(nil), // 0: StatusNotifyUnreadChat
	(*StatusNotifyFunction)(nil),   // 1: StatusNotifyFunction
	(*StatusNotifyRequest)(nil),    // 2: StatusNotifyRequest
	(*ChatContact)(nil),            // 3: ChatContact
	(*StatusNotifyResponse)(nil),   // 4: StatusNotifyResponse
	(*BaseRequest)(nil),            // 5: BaseRequest
	(*BaseResponse)(nil),           // 6: BaseResponse
}
var file_StatusNotify_proto_depIdxs = []int32{
	5, // 0: StatusNotifyRequest.baseRequest:type_name -> BaseRequest
	0, // 1: StatusNotifyRequest.unreadChatList:type_name -> StatusNotifyUnreadChat
	1, // 2: StatusNotifyRequest.function:type_name -> StatusNotifyFunction
	1, // 3: StatusNotifyRequest.unreadFunctionList:type_name -> StatusNotifyFunction
	6, // 4: StatusNotifyResponse.BaseResponse:type_name -> BaseResponse
	3, // 5: StatusNotifyResponse.ChatContactList:type_name -> ChatContact
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_StatusNotify_proto_init() }
func file_StatusNotify_proto_init() {
	if File_StatusNotify_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_StatusNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusNotifyUnreadChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StatusNotify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusNotifyFunction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StatusNotify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusNotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StatusNotify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatContact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StatusNotify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusNotifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_StatusNotify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_StatusNotify_proto_goTypes,
		DependencyIndexes: file_StatusNotify_proto_depIdxs,
		MessageInfos:      file_StatusNotify_proto_msgTypes,
	}.Build()
	File_StatusNotify_proto = out.File
	file_StatusNotify_proto_rawDesc = nil
	file_StatusNotify_proto_goTypes = nil
	file_StatusNotify_proto_depIdxs = nil
}
