// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: UploadEmoji.proto

package micromsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmojiUploadInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Md5           *string           `protobuf:"bytes,1,opt,name=md5" json:"md5,omitempty"`
	StartPos      *int32            `protobuf:"varint,2,req,name=startPos" json:"startPos,omitempty"`
	TotalLen      *int32            `protobuf:"varint,3,req,name=totalLen" json:"totalLen,omitempty"`
	EmojiBuffer   *SKBuiltinBufferT `protobuf:"bytes,4,req,name=emojiBuffer" json:"emojiBuffer,omitempty"`
	Type          *int32            `protobuf:"varint,5,req,name=type" json:"type,omitempty"`
	ToUserName    *string           `protobuf:"bytes,6,opt,name=toUserName" json:"toUserName,omitempty"`
	ExternXml     *string           `protobuf:"bytes,7,opt,name=externXml" json:"externXml,omitempty"`
	Report        *string           `protobuf:"bytes,8,opt,name=report" json:"report,omitempty"`
	ClientMsgId   *string           `protobuf:"bytes,9,opt,name=clientMsgId" json:"clientMsgId,omitempty"`
	MsgSource     *string           `protobuf:"bytes,10,opt,name=msgSource" json:"msgSource,omitempty"`
	NewXmlFlag    *int32            `protobuf:"varint,11,opt,name=newXmlFlag" json:"newXmlFlag,omitempty"`
	SendMsgTicket *string           `protobuf:"bytes,12,opt,name=sendMsgTicket" json:"sendMsgTicket,omitempty"`
}

func (x *EmojiUploadInfoReq) Reset() {
	*x = EmojiUploadInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UploadEmoji_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmojiUploadInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmojiUploadInfoReq) ProtoMessage() {}

func (x *EmojiUploadInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_UploadEmoji_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmojiUploadInfoReq.ProtoReflect.Descriptor instead.
func (*EmojiUploadInfoReq) Descriptor() ([]byte, []int) {
	return file_UploadEmoji_proto_rawDescGZIP(), []int{0}
}

func (x *EmojiUploadInfoReq) GetMd5() string {
	if x != nil && x.Md5 != nil {
		return *x.Md5
	}
	return ""
}

func (x *EmojiUploadInfoReq) GetStartPos() int32 {
	if x != nil && x.StartPos != nil {
		return *x.StartPos
	}
	return 0
}

func (x *EmojiUploadInfoReq) GetTotalLen() int32 {
	if x != nil && x.TotalLen != nil {
		return *x.TotalLen
	}
	return 0
}

func (x *EmojiUploadInfoReq) GetEmojiBuffer() *SKBuiltinBufferT {
	if x != nil {
		return x.EmojiBuffer
	}
	return nil
}

func (x *EmojiUploadInfoReq) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *EmojiUploadInfoReq) GetToUserName() string {
	if x != nil && x.ToUserName != nil {
		return *x.ToUserName
	}
	return ""
}

func (x *EmojiUploadInfoReq) GetExternXml() string {
	if x != nil && x.ExternXml != nil {
		return *x.ExternXml
	}
	return ""
}

func (x *EmojiUploadInfoReq) GetReport() string {
	if x != nil && x.Report != nil {
		return *x.Report
	}
	return ""
}

func (x *EmojiUploadInfoReq) GetClientMsgId() string {
	if x != nil && x.ClientMsgId != nil {
		return *x.ClientMsgId
	}
	return ""
}

func (x *EmojiUploadInfoReq) GetMsgSource() string {
	if x != nil && x.MsgSource != nil {
		return *x.MsgSource
	}
	return ""
}

func (x *EmojiUploadInfoReq) GetNewXmlFlag() int32 {
	if x != nil && x.NewXmlFlag != nil {
		return *x.NewXmlFlag
	}
	return 0
}

func (x *EmojiUploadInfoReq) GetSendMsgTicket() string {
	if x != nil && x.SendMsgTicket != nil {
		return *x.SendMsgTicket
	}
	return ""
}

type UploadEmojiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest    *BaseRequest          `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	EmojiItemCount *int32                `protobuf:"varint,2,req,name=emojiItemCount" json:"emojiItemCount,omitempty"`
	EmojiItem      []*EmojiUploadInfoReq `protobuf:"bytes,3,rep,name=emojiItem" json:"emojiItem,omitempty"`
}

func (x *UploadEmojiRequest) Reset() {
	*x = UploadEmojiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UploadEmoji_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadEmojiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadEmojiRequest) ProtoMessage() {}

func (x *UploadEmojiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UploadEmoji_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadEmojiRequest.ProtoReflect.Descriptor instead.
func (*UploadEmojiRequest) Descriptor() ([]byte, []int) {
	return file_UploadEmoji_proto_rawDescGZIP(), []int{1}
}

func (x *UploadEmojiRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *UploadEmojiRequest) GetEmojiItemCount() int32 {
	if x != nil && x.EmojiItemCount != nil {
		return *x.EmojiItemCount
	}
	return 0
}

func (x *UploadEmojiRequest) GetEmojiItem() []*EmojiUploadInfoReq {
	if x != nil {
		return x.EmojiItem
	}
	return nil
}

type EmojiUploadInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      *int32  `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	StartPos *int32  `protobuf:"varint,2,req,name=startPos" json:"startPos,omitempty"`
	TotalLen *int32  `protobuf:"varint,3,req,name=totalLen" json:"totalLen,omitempty"`
	Md5      *string `protobuf:"bytes,4,opt,name=md5" json:"md5,omitempty"`
	MsgId    *uint32 `protobuf:"varint,5,req,name=msgId" json:"msgId,omitempty"`
	NewMsgId *uint64 `protobuf:"varint,6,opt,name=newMsgId" json:"newMsgId,omitempty"`
}

func (x *EmojiUploadInfoResp) Reset() {
	*x = EmojiUploadInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UploadEmoji_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmojiUploadInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmojiUploadInfoResp) ProtoMessage() {}

func (x *EmojiUploadInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_UploadEmoji_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmojiUploadInfoResp.ProtoReflect.Descriptor instead.
func (*EmojiUploadInfoResp) Descriptor() ([]byte, []int) {
	return file_UploadEmoji_proto_rawDescGZIP(), []int{2}
}

func (x *EmojiUploadInfoResp) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *EmojiUploadInfoResp) GetStartPos() int32 {
	if x != nil && x.StartPos != nil {
		return *x.StartPos
	}
	return 0
}

func (x *EmojiUploadInfoResp) GetTotalLen() int32 {
	if x != nil && x.TotalLen != nil {
		return *x.TotalLen
	}
	return 0
}

func (x *EmojiUploadInfoResp) GetMd5() string {
	if x != nil && x.Md5 != nil {
		return *x.Md5
	}
	return ""
}

func (x *EmojiUploadInfoResp) GetMsgId() uint32 {
	if x != nil && x.MsgId != nil {
		return *x.MsgId
	}
	return 0
}

func (x *EmojiUploadInfoResp) GetNewMsgId() uint64 {
	if x != nil && x.NewMsgId != nil {
		return *x.NewMsgId
	}
	return 0
}

type UploadEmojiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse   *BaseResponse          `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
	EmojiItemCount *int32                 `protobuf:"varint,2,req,name=emojiItemCount" json:"emojiItemCount,omitempty"`
	EmojiItem      []*EmojiUploadInfoResp `protobuf:"bytes,3,rep,name=emojiItem" json:"emojiItem,omitempty"`
	ActionFlag     *uint32                `protobuf:"varint,4,opt,name=actionFlag" json:"actionFlag,omitempty"`
}

func (x *UploadEmojiResponse) Reset() {
	*x = UploadEmojiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UploadEmoji_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadEmojiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadEmojiResponse) ProtoMessage() {}

func (x *UploadEmojiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_UploadEmoji_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadEmojiResponse.ProtoReflect.Descriptor instead.
func (*UploadEmojiResponse) Descriptor() ([]byte, []int) {
	return file_UploadEmoji_proto_rawDescGZIP(), []int{3}
}

func (x *UploadEmojiResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *UploadEmojiResponse) GetEmojiItemCount() int32 {
	if x != nil && x.EmojiItemCount != nil {
		return *x.EmojiItemCount
	}
	return 0
}

func (x *UploadEmojiResponse) GetEmojiItem() []*EmojiUploadInfoResp {
	if x != nil {
		return x.EmojiItem
	}
	return nil
}

func (x *UploadEmojiResponse) GetActionFlag() uint32 {
	if x != nil && x.ActionFlag != nil {
		return *x.ActionFlag
	}
	return 0
}

var File_UploadEmoji_proto protoreflect.FileDescriptor

var file_UploadEmoji_proto_rawDesc = []byte{
	0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x4d, 0x73, 0x67, 0x42, 0x61, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x03, 0x0a, 0x12, 0x45, 0x6d, 0x6f, 0x6a,
	0x69, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x05, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x12, 0x34, 0x0a, 0x0b, 0x65, 0x6d, 0x6f, 0x6a,
	0x69, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x5f,
	0x74, 0x52, 0x0b, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x02, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x58, 0x6d, 0x6c, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x58, 0x6d, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x73,
	0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d,
	0x73, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x58,
	0x6d, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x65,
	0x77, 0x58, 0x6d, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x64,
	0x4d, 0x73, 0x67, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x9f,
	0x01, 0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x49, 0x74,
	0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0e, 0x65,
	0x6d, 0x6f, 0x6a, 0x69, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x31, 0x0a,
	0x09, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x52, 0x09, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x49, 0x74, 0x65, 0x6d,
	0x22, 0xa3, 0x01, 0x0a, 0x13, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c,
	0x65, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c,
	0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x64, 0x35, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x05, 0x20,
	0x02, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65,
	0x77, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6e, 0x65,
	0x77, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x22, 0xc4, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0e, 0x65, 0x6d, 0x6f, 0x6a, 0x69,
	0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x09, 0x65, 0x6d, 0x6f,
	0x6a, 0x69, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x45,
	0x6d, 0x6f, 0x6a, 0x69, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x52, 0x09, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x0a,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6c, 0x61, 0x67, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d, 0x73, 0x67,
}

var (
	file_UploadEmoji_proto_rawDescOnce sync.Once
	file_UploadEmoji_proto_rawDescData = file_UploadEmoji_proto_rawDesc
)

func file_UploadEmoji_proto_rawDescGZIP() []byte {
	file_UploadEmoji_proto_rawDescOnce.Do(func() {
		file_UploadEmoji_proto_rawDescData = protoimpl.X.CompressGZIP(file_UploadEmoji_proto_rawDescData)
	})
	return file_UploadEmoji_proto_rawDescData
}

var file_UploadEmoji_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_UploadEmoji_proto_goTypes = []interface{}{
	(*EmojiUploadInfoReq)(nil),  // 0: EmojiUploadInfoReq
	(*UploadEmojiRequest)(nil),  // 1: UploadEmojiRequest
	(*EmojiUploadInfoResp)(nil), // 2: EmojiUploadInfoResp
	(*UploadEmojiResponse)(nil), // 3: UploadEmojiResponse
	(*SKBuiltinBufferT)(nil),    // 4: SKBuiltinBuffer_t
	(*BaseRequest)(nil),         // 5: BaseRequest
	(*BaseResponse)(nil),        // 6: BaseResponse
}
var file_UploadEmoji_proto_depIdxs = []int32{
	4, // 0: EmojiUploadInfoReq.emojiBuffer:type_name -> SKBuiltinBuffer_t
	5, // 1: UploadEmojiRequest.baseRequest:type_name -> BaseRequest
	0, // 2: UploadEmojiRequest.emojiItem:type_name -> EmojiUploadInfoReq
	6, // 3: UploadEmojiResponse.baseResponse:type_name -> BaseResponse
	2, // 4: UploadEmojiResponse.emojiItem:type_name -> EmojiUploadInfoResp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_UploadEmoji_proto_init() }
func file_UploadEmoji_proto_init() {
	if File_UploadEmoji_proto != nil {
		return
	}
	file_MicroMsgBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_UploadEmoji_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmojiUploadInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UploadEmoji_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadEmojiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UploadEmoji_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmojiUploadInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UploadEmoji_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadEmojiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_UploadEmoji_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UploadEmoji_proto_goTypes,
		DependencyIndexes: file_UploadEmoji_proto_depIdxs,
		MessageInfos:      file_UploadEmoji_proto_msgTypes,
	}.Build()
	File_UploadEmoji_proto = out.File
	file_UploadEmoji_proto_rawDesc = nil
	file_UploadEmoji_proto_goTypes = nil
	file_UploadEmoji_proto_depIdxs = nil
}
